CREATE PROCEDURE [ods].[uspODSCPR_TICKCUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[CPR_TICKC]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[CPR_TICKC] [t]
        INNER JOIN [stage].[CPR_TICKC] [s]
            ON [t].[CPK_TICKC] = [s].[CPK_TICKC]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[CPR_TICKC]
    (
 		[CPK_TICKC],
		[TICKNO] ,
		[NO] ,
		[MRN],
		[NAME_],
		[CODE] ,
		[DORMCODE],
		[NEXTCODE] ,
		[PRN],
		[DEFQUANT],
		[SAVQUANT],
		[RAWQUANT],
		[CATTEXT],
		[PARTTYPE],
		[EXP],
		[RXDAYS] ,
		[RXCODE],
		[KNUM] ,
		[LOTNUM],
		[PARTNUM],
		[COST],
		[PRICE],
		[SPRICE],
		[BPRICE],
		[TOBILL],
		[ONDT],
		[SUPPLY],
		[CHGCODE],
		[CDAFLAG],
		[CADJUSTRES],
		[CDISPOSITN],
		[CFREQ],
		[LREFILL] ,
		[OTNO] ,
		[INITS],
		[DUMMY],
		[FREQUENCY],
		[LABLOGNO] ,
		[SUPLOCNO] ,
		[MAKERR],
		[UNITSVIAL] ,
		[VIALS] ,
		[DELFLAG],
		[TOUCHDATE],
		[CHGBYHOST],
		[CREATEDON],
		[CREATEDBY],
		[RAWSPK] ,
		[DEDUCTED] ,
		[TAXABLE],
		[DOCKEY] ,
		[DOCTABLE],
		[REQAUTH] ,
		[CFK_INSVERI] ,
		[STOPRR] ,
		[FK_POPUPDATA_RENTAL_PRICETYPE] ,
		[UOMTEXT],
		[UOMEACHES],
		[PICKUP] ,
		[EXCHANGEKEY] ,
		[SELECTSN] ,
		[SCANPROC] ,
		[QUOTEITEM] ,
		[ACCEPTASSIGNMENT],
		[EXPECTED],
		[PATIENTEA],
		[CFK_INSCOMP] ,
		[PATIENTPERCENT] ,
		[CFK_PATINS] ,
		[MCRNOTCOVERED] ,
		[NOTCOVERED] ,
		[CFK_LABELS] ,
		[DXCODE],
		[NARRATIVE],
		[MODIFIER],
		[BILLNO] ,
		[DIRECTSHIP_PRICE],
		[DIRECTSHIP_PRICESOURCE],
		[DIRECTSHIP_BACKORDERQTY],
		[DIRECTSHIP_AVAILABLE] ,
		[LINENUMBER] ,
		[SHIPPEDQTY],
		[REORDER],
		[ASSISTMEDSENT] ,
		[CFK_CBA_PC] ,
		[CBA_KE] ,
		[NEEDUPDATE] ,
		[AUTHOVERRIDE] ,
		[LOANER] ,
		[BILLED_TAX],
		[EXPECTED_TAX],
		[TAXABLE_INT] ,
		[CFK_TAXCODES] ,
		[disc],
		[discprice],
		[retquant],
		[fsaeligible] ,
		[isdiscardquantity] ,
        [EffectiveDate],
        [ExpirationDate],
        [CurrentRowFlag],
        [DeleteRowFlag],
        [InsertDate]
    )
    SELECT 	
		[CPK_TICKC],
		[TICKNO] ,
		[NO] ,
		[MRN],
		[NAME_],
		[CODE] ,
		[DORMCODE],
		[NEXTCODE] ,
		[PRN],
		[DEFQUANT],
		[SAVQUANT],
		[RAWQUANT],
		[CATTEXT],
		[PARTTYPE],
		[EXP],
		[RXDAYS] ,
		[RXCODE],
		[KNUM] ,
		[LOTNUM],
		[PARTNUM],
		[COST],
		[PRICE],
		[SPRICE],
		[BPRICE],
		[TOBILL],
		[ONDT],
		[SUPPLY],
		[CHGCODE],
		[CDAFLAG],
		[CADJUSTRES],
		[CDISPOSITN],
		[CFREQ],
		[LREFILL] ,
		[OTNO] ,
		[INITS],
		[DUMMY],
		[FREQUENCY],
		[LABLOGNO] ,
		[SUPLOCNO] ,
		[MAKERR],
		[UNITSVIAL] ,
		[VIALS] ,
		[DELFLAG],
		[TOUCHDATE],
		[CHGBYHOST],
		[CREATEDON],
		[CREATEDBY],
		[RAWSPK] ,
		[DEDUCTED] ,
		[TAXABLE],
		[DOCKEY] ,
		[DOCTABLE],
		[REQAUTH] ,
		[CFK_INSVERI] ,
		[STOPRR] ,
		[FK_POPUPDATA_RENTAL_PRICETYPE] ,
		[UOMTEXT],
		[UOMEACHES],
		[PICKUP] ,
		[EXCHANGEKEY] ,
		[SELECTSN] ,
		[SCANPROC] ,
		[QUOTEITEM] ,
		[ACCEPTASSIGNMENT],
		[EXPECTED],
		[PATIENTEA],
		[CFK_INSCOMP] ,
		[PATIENTPERCENT] ,
		[CFK_PATINS] ,
		[MCRNOTCOVERED] ,
		[NOTCOVERED] ,
		[CFK_LABELS] ,
		[DXCODE],
		[NARRATIVE],
		[MODIFIER],
		[BILLNO] ,
		[DIRECTSHIP_PRICE],
		[DIRECTSHIP_PRICESOURCE],
		[DIRECTSHIP_BACKORDERQTY],
		[DIRECTSHIP_AVAILABLE] ,
		[LINENUMBER] ,
		[SHIPPEDQTY],
		[REORDER],
		[ASSISTMEDSENT] ,
		[CFK_CBA_PC] ,
		[CBA_KE] ,
		[NEEDUPDATE] ,
		[AUTHOVERRIDE] ,
		[LOANER] ,
		[BILLED_TAX],
		[EXPECTED_TAX],
		[TAXABLE_INT] ,
		[CFK_TAXCODES] ,
		[disc],
		[discprice],
		[retquant],
		[fsaeligible] ,
		[isdiscardquantity] ,
        @DateTime AS [EffectiveDate],
        NULL AS [ExpirationDate],
        1 AS [CurrentRowFlag],
        0 AS [DeleteRowFlag],
        @DateTime AS [InsertDate]
    FROM [stage].[CPR_TICKC] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[CPR_TICKC] AS [t]
        WHERE [t].[CPK_TICKC] = [s].[CPK_TICKC]
              AND [t].[CurrentRowFlag] = 1
    );

END;

