CREATE PROCEDURE [ods].[uspODSNG_PIVC_Orders_Upsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_PIVC_Orders_]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_PIVC_Orders_] [t]
        INNER JOIN [stage].[NG_PIVC_Orders_] [s]
            ON [t].[seq_no] = [s].[seq_no]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_PIVC_Orders_]
    ( 
      [enterprise_id]
      ,[practice_id]
      ,[person_id]
      ,[seq_no]
      ,[created_by]
      ,[create_timestamp]
      ,[modified_by]
      ,[modify_timestamp]
      ,[create_timestamp_tz]
      ,[modify_timestamp_tz]
      ,[row_timestamp]
      ,[Benefits_Status]
      ,[Diagnosis1_Code]
      ,[Diagnosis1_Desciption]
      ,[Diagnosis2_Code]
      ,[Diagnosis2_Desciption]
      ,[Diagnosis3_Code]
      ,[Diagnosis3_Desciption]
      ,[Expiration_Date]
      ,[Expiration_Dose]
      ,[Expire_Mode]
      ,[Med_Provided]
      ,[Med1_InitialDose]
      ,[Med1_InitialDose_Units]
      ,[Med1_OtherDose]
      ,[Med1_OtherDose_Units]
      ,[Med1_SecondDose]
      ,[Med1_SecondDose_Units]
      ,[Med2_InitialDose]
      ,[Med2_InitialDose_Units]
      ,[Med2_OtherDose]
      ,[Med2_OtherDose_Units]
      ,[Med2_SecondDose]
      ,[Med2_SecondDose_Units]
      ,[Med3_InitialDose]
      ,[Med3_InitialDose_Units]
      ,[Med3_OtherDose]
      ,[Med3_OtherDose_Units]
      ,[Med3_SecondDose]
      ,[Med3_SecondDose_Units]
      ,[Med4_InitialDose]
      ,[Med4_InitialDose_Units]
      ,[Med4_OtherDose]
      ,[Med4_OtherDose_Units]
      ,[Med4_SecondDose]
      ,[Med4_SecondDose_Units]
      ,[Med5_InitialDose]
      ,[Med5_InitialDose_Units]
      ,[Med5_OtherDose]
      ,[Med5_OtherDose_Units]
      ,[Med5_SecondDose]
      ,[Med5_SecondDose_Units]
      ,[Med6_InitialDose]
      ,[Med6_InitialDose_Units]
      ,[Med6_OtherDose]
      ,[Med6_OtherDose_Units]
      ,[Med6_SecondDose]
      ,[Med6_SecondDose_Units]
      ,[Med7_InitialDose]
      ,[Med7_InitialDose_Units]
      ,[Med7_OtherDose]
      ,[Med7_OtherDose_Units]
      ,[Med7_SecondDose]
      ,[Med7_SecondDose_Units]
      ,[Med8_InitialDose]
      ,[Med8_InitialDose_Units]
      ,[Med8_OtherDose]
      ,[Med8_OtherDose_Units]
      ,[Med8_SecondDose]
      ,[Med8_SecondDose_Units]
      ,[Medication1]
      ,[Medication2]
      ,[Medication3]
      ,[Medication4]
      ,[Medication5]
      ,[Medication6]
      ,[Medication7]
      ,[Medication8]
      ,[MP_UpdatedBy]
      ,[MP_UpdatedOn]
      ,[Notes]
      ,[Order_Date]
      ,[Order_Status]
      ,[Order_Type]
      ,[Ordering_Provider_id]
      ,[Ordering_Provider_Name]
      ,[OrderType_Event_id]
      ,[Patient_Wt_kg]
      ,[Patient_Wt_lbs]
      ,[PreMed1]
      ,[PreMed1_Dose]
      ,[PreMed1_Units]
      ,[PreMed2]
      ,[PreMed2_Dose]
      ,[PreMed2_Units]
      ,[PreMed3]
      ,[PreMed3_Dose]
      ,[PreMed3_Units]
      ,[Status_UpdatedBy]
      ,[Status_UpdatedOn]
      ,[Patient_Ht_cm]
      ,[Patient_Ht_In]
      ,[Auth_Code]
      ,[Auth_Expiration_Date]
      ,[Auth_Required]
      ,[Service_Location]
      ,[Non_Billable]
      ,[CAS]
      ,[Document_id]
      ,[Frequency]
      ,[NextDoseDue]
      ,[Original_Orderid]
      ,[PreMed4]
      ,[PreMed4_Dose]
      ,[PreMed4_Units]
      ,[Reason]
      ,[Therapy_Started]
      ,[MedProvided_Type]
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT [enterprise_id]
      ,[practice_id]
      ,[person_id]
      ,[seq_no]
      ,[created_by]
      ,[create_timestamp]
      ,[modified_by]
      ,[modify_timestamp]
      ,[create_timestamp_tz]
      ,[modify_timestamp_tz]
      ,[row_timestamp]
      ,[Benefits_Status]
      ,[Diagnosis1_Code]
      ,[Diagnosis1_Desciption]
      ,[Diagnosis2_Code]
      ,[Diagnosis2_Desciption]
      ,[Diagnosis3_Code]
      ,[Diagnosis3_Desciption]
      ,[Expiration_Date]
      ,[Expiration_Dose]
      ,[Expire_Mode]
      ,[Med_Provided]
      ,[Med1_InitialDose]
      ,[Med1_InitialDose_Units]
      ,[Med1_OtherDose]
      ,[Med1_OtherDose_Units]
      ,[Med1_SecondDose]
      ,[Med1_SecondDose_Units]
      ,[Med2_InitialDose]
      ,[Med2_InitialDose_Units]
      ,[Med2_OtherDose]
      ,[Med2_OtherDose_Units]
      ,[Med2_SecondDose]
      ,[Med2_SecondDose_Units]
      ,[Med3_InitialDose]
      ,[Med3_InitialDose_Units]
      ,[Med3_OtherDose]
      ,[Med3_OtherDose_Units]
      ,[Med3_SecondDose]
      ,[Med3_SecondDose_Units]
      ,[Med4_InitialDose]
      ,[Med4_InitialDose_Units]
      ,[Med4_OtherDose]
      ,[Med4_OtherDose_Units]
      ,[Med4_SecondDose]
      ,[Med4_SecondDose_Units]
      ,[Med5_InitialDose]
      ,[Med5_InitialDose_Units]
      ,[Med5_OtherDose]
      ,[Med5_OtherDose_Units]
      ,[Med5_SecondDose]
      ,[Med5_SecondDose_Units]
      ,[Med6_InitialDose]
      ,[Med6_InitialDose_Units]
      ,[Med6_OtherDose]
      ,[Med6_OtherDose_Units]
      ,[Med6_SecondDose]
      ,[Med6_SecondDose_Units]
      ,[Med7_InitialDose]
      ,[Med7_InitialDose_Units]
      ,[Med7_OtherDose]
      ,[Med7_OtherDose_Units]
      ,[Med7_SecondDose]
      ,[Med7_SecondDose_Units]
      ,[Med8_InitialDose]
      ,[Med8_InitialDose_Units]
      ,[Med8_OtherDose]
      ,[Med8_OtherDose_Units]
      ,[Med8_SecondDose]
      ,[Med8_SecondDose_Units]
      ,[Medication1]
      ,[Medication2]
      ,[Medication3]
      ,[Medication4]
      ,[Medication5]
      ,[Medication6]
      ,[Medication7]
      ,[Medication8]
      ,[MP_UpdatedBy]
      ,[MP_UpdatedOn]
      ,[Notes]
      ,[Order_Date]
      ,[Order_Status]
      ,[Order_Type]
      ,[Ordering_Provider_id]
      ,[Ordering_Provider_Name]
      ,[OrderType_Event_id]
      ,[Patient_Wt_kg]
      ,[Patient_Wt_lbs]
      ,[PreMed1]
      ,[PreMed1_Dose]
      ,[PreMed1_Units]
      ,[PreMed2]
      ,[PreMed2_Dose]
      ,[PreMed2_Units]
      ,[PreMed3]
      ,[PreMed3_Dose]
      ,[PreMed3_Units]
      ,[Status_UpdatedBy]
      ,[Status_UpdatedOn]
      ,[Patient_Ht_cm]
      ,[Patient_Ht_In]
      ,[Auth_Code]
      ,[Auth_Expiration_Date]
      ,[Auth_Required]
      ,[Service_Location]
      ,[Non_Billable]
      ,[CAS]
      ,[Document_id]
      ,[Frequency]
      ,[NextDoseDue]
      ,[Original_Orderid]
      ,[PreMed4]
      ,[PreMed4_Dose]
      ,[PreMed4_Units]
      ,[Reason]
      ,[Therapy_Started]
      ,[MedProvided_Type]
      ,@DateTime AS [EffectiveDate]
      ,NULL AS [ExpirationDate]
      ,1 AS [CurrentRowFlag]
      ,0 AS [DeleteRowFlag]
      ,@DateTime AS [InsertDate]
    FROM [stage].[NG_PIVC_Orders_] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_PIVC_Orders_] AS [t]
        WHERE [t].[seq_no] = [s].[seq_no]
              AND [t].[CurrentRowFlag] = 1
    );  

END;