CREATE PROCEDURE [ods].[uspODSCPR_BILLEDUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[CPR_BILLED]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[CPR_BILLED] [t]
        INNER JOIN [stage].[CPR_BILLED] [s]
            ON [t].[CPK_BILLED] = [s].[CPK_BILLED]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[CPR_BILLED]
    (
		[CPK_BILLED],
		[MRN],
		[BILLNO],
		[BILLTXT],
		[BILLTYPE],
		[DATEBILLED],
		[FROM_],
		[TO_],
		[PAYOR],
		[CHARGE],
		[ALLOWED],
		[PAYREC],
		[ADJUSTAMT],
		[ADJDATE],
		[ADJTYPE],
		[DESCRIPT],
		[CHECKNO],
		[CHECKDATE],
		[DEPOSITED],
		[BALANCE],
		[OBALANCE],
		[TOTPAYMENT],
		[TOTADJ],
		[COST],
		[INVOICETYP],
		[TEXTTYPE],
		[REQUIRECMN],
		[CMNTYPE],
		[CERTONFILE],
		[CPRCMNNO],
		[PRINTYN],
		[SENTYN],
		[PID],
		[LASTSENT],
		[TAX],
		[LAST_NAME],
		[FIRST_NAME],
		[BATCHPAY],
		[RESUB],
		[REVCODE],
		[MC2COMP],
		[NURSING],
		[PAYTYPE],
		[ZERO],
		[YESPOST],
		[SORTFLD],
		[COLLNOTE],
		[REMARK],
		[CLOSENUM],
		[SCRIPTEXT],
		[LINE9],
		[RXDATE],
		[HOSPITAL],
		[HOSPSITE],
		[CLAIMPAID],
		[PAMC],
		[IVRT],
		[MD],
		[IDNUMD],
		[RXREF],
		[RXDDATE],
		[RXPDATE],
		[MMAFORMID],
		[MMAFORMFOR],
		[ZEROOUT],
		[INSNO],
		[PH_NO],
		[BATCHPRINT],
		[RESPONSIBL],
		[TXCREATED],
		[TRANSMIT],
		[UC_NO],
		[BATCHNO],
		[PI_NO],
		[DELFLAG],
		[TOUCHDATE],
		[CHGBYHOST],
		[CREATEDON],
		[CREATEDBY] ,
		[ONHOLDMSG],
		[POS],
		[PMTTYPE],
		[CARDTYPE],
		[DENIALEXP],
		[CFK_RTBSTAT],
		[CFK_CLIENT],
		[CFK_REFSOURC],
		[BILLASDENIAL],
		[CFK_POSTERMID],
		[CROSSEDOVER],
		[CFK_RECRENT],
		[CFK_RENTALS],
		[cfk_labels],
		[rtpbatchnum],
		[orig_billno],
		[cfk_pnnames_status],
        [EffectiveDate],
        [ExpirationDate],
        [CurrentRowFlag],
        [DeleteRowFlag],
        [InsertDate]
    )
    SELECT 	[CPK_BILLED],
			[MRN],
			[BILLNO],
			[BILLTXT],
			[BILLTYPE],
			[DATEBILLED],
			[FROM_],
			[TO_],
			[PAYOR],
			[CHARGE],
			[ALLOWED],
			[PAYREC],
			[ADJUSTAMT],
			[ADJDATE],
			[ADJTYPE],
			[DESCRIPT],
			[CHECKNO],
			[CHECKDATE],
			[DEPOSITED],
			[BALANCE],
			[OBALANCE],
			[TOTPAYMENT],
			[TOTADJ],
			[COST],
			[INVOICETYP],
			[TEXTTYPE],
			[REQUIRECMN],
			[CMNTYPE],
			[CERTONFILE],
			[CPRCMNNO],
			[PRINTYN],
			[SENTYN],
			[PID],
			[LASTSENT],
			[TAX],
			[LAST_NAME],
			[FIRST_NAME],
			[BATCHPAY],
			[RESUB],
			[REVCODE],
			[MC2COMP],
			[NURSING],
			[PAYTYPE],
			[ZERO],
			[YESPOST],
			[SORTFLD],
			[COLLNOTE],
			[REMARK],
			[CLOSENUM],
			[SCRIPTEXT],
			[LINE9],
			[RXDATE],
			[HOSPITAL],
			[HOSPSITE],
			[CLAIMPAID],
			[PAMC],
			[IVRT],
			[MD],
			[IDNUMD],
			[RXREF],
			[RXDDATE],
			[RXPDATE],
			[MMAFORMID],
			[MMAFORMFOR],
			[ZEROOUT],
			[INSNO],
			[PH_NO],
			[BATCHPRINT],
			[RESPONSIBL],
			[TXCREATED],
			[TRANSMIT],
			[UC_NO],
			[BATCHNO],
			[PI_NO],
			[DELFLAG],
			[TOUCHDATE],
			[CHGBYHOST],
			[CREATEDON],
			[CREATEDBY] ,
			[ONHOLDMSG],
			[POS],
			[PMTTYPE],
			[CARDTYPE],
			[DENIALEXP],
			[CFK_RTBSTAT],
			[CFK_CLIENT],
			[CFK_REFSOURC],
			[BILLASDENIAL],
			[CFK_POSTERMID],
			[CROSSEDOVER],
			[CFK_RECRENT],
			[CFK_RENTALS],
			[cfk_labels],
			[rtpbatchnum],
			[orig_billno],
			[cfk_pnnames_status],
			@DateTime AS [EffectiveDate],
			NULL AS [ExpirationDate],
			1 AS [CurrentRowFlag],
			0 AS [DeleteRowFlag],
			@DateTime AS [InsertDate]
    FROM [stage].[CPR_BILLED] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[CPR_BILLED] AS [t]
        WHERE [t].[CPK_BILLED] = [s].[CPK_BILLED]
              AND [t].[CurrentRowFlag] = 1
    );

END;
