CREATE PROCEDURE [ods].[uspODSNG_PIVC_Infusion_Upsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_PIVC_Infusion_]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_PIVC_Infusion_] [t]
        INNER JOIN [stage].[NG_PIVC_Infusion_] [s]
            ON [t].[enc_id] = [s].[enc_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_PIVC_Infusion_]
    ( [enterprise_id]
      ,[practice_id]
      ,[person_id]
      ,[enc_id]
      ,[created_by]
      ,[create_timestamp]
      ,[modified_by]
      ,[modify_timestamp]
      ,[create_timestamp_tz]
      ,[modify_timestamp_tz]
      ,[row_timestamp]
      ,[Diagnosis1_Code]
      ,[Diagnosis1_Description]
      ,[Diagnosis2_Code]
      ,[Diagnosis2_Description]
      ,[Diagnosis3_Code]
      ,[Diagnosis3_Description]
      ,[Discharge_BP]
      ,[Discharge_HR]
      ,[Discharge_Instn_Given]
      ,[Discharge_Instructions]
      ,[Discharge_Pain]
      ,[Discharge_RR]
      ,[Discharge_SpO2]
      ,[Discharge_Temp]
      ,[Discharge_Vitals_Time]
      ,[Final_Sign_Date]
      ,[Final_Sign_InvBillingError]
      ,[Final_Sign_InvBillingUpdate]
      ,[Final_Sign_Time]
      ,[Final_Signed_By]
      ,[Internal_Provider_id]
      ,[Internal_Provider_Name]
      ,[Ivstart_Access]
      ,[Ivstart_Central_Line]
      ,[Ivstart_Lumen_Count]
      ,[Ivstart_Midline_Type]
      ,[Ivstart_OtherAccess]
      ,[Ivstart_PICC_ArmCircum]
      ,[Ivstart_PICC_Pulled]
      ,[Ivstart_PICC_Type]
      ,[Ivstart_PIV]
      ,[Ivstart_PIV_Attempts]
      ,[Ivstart_PIV_Location]
      ,[Ivstart_PIV_Vein]
      ,[Ivstart_PORT_AccessedToday]
      ,[Ivstart_PORT_Type]
      ,[LMP_NA]
      ,[Location_id]
      ,[Med_Provided]
      ,[No_Medications]
      ,[Order_Description]
      ,[Order_seq_no]
      ,[Ordering_Provider_id]
      ,[Ordering_Provider_Name]
      ,[Partial_Sign_Date]
      ,[Partial_Sign_Time]
      ,[Partial_Signed_By]
      ,[Patient_Wt_Kg]
      ,[Patient_Wt_lbs]
      ,[pe_Accompanied_by]
      ,[pe_Ambulatory]
      ,[pe_Cardio_Comments]
      ,[pe_Cardio_Edema]
      ,[pe_Cardio_HRR]
      ,[pe_Distress]
      ,[pe_Distress_Comments]
      ,[pe_Gastro_ABDSoft]
      ,[pe_Gastro_BSounds]
      ,[pe_Gastro_Comments]
      ,[pe_Gastro_Tender]
      ,[pe_IVSite_CleanDry]
      ,[pe_IVSite_Comments]
      ,[pe_IVSite_Pain]
      ,[pe_IVSite_Redness]
      ,[pe_IVSite_SSInfection]
      ,[pe_Neuro_Comments]
      ,[pe_Neuro_Normal]
      ,[pe_Neuro_Pain]
      ,[pe_Neuro_PERRLA]
      ,[pe_Oriented]
      ,[pe_Oriented_Comments]
      ,[pe_Other_Comments]
      ,[pe_Pulmonary_Comments]
      ,[pe_Pulmonary_DecreasedBS]
      ,[pe_Pulmonary_LungsClear]
      ,[pe_Pulmonary_SOB]
      ,[pe_Pulmonary_Wheezes]
      ,[pe_Skin_Color]
      ,[pe_Skin_Comments]
      ,[pe_Skin_OralMuscosa]
      ,[pe_Skin_Turgor]
      ,[pe_Skin_WarmDry_Cool]
      ,[pre_Chest_Xray]
      ,[pre_EpiPen]
      ,[pre_EpiPen_Expiry]
      ,[pre_EpiPen_Guide]
      ,[pre_HepB]
      ,[pre_TB_Test]
      ,[PRN_Sign_Date]
      ,[PRN_Sign_Time]
      ,[PRN_Signed_By]
      ,[PRNMeds]
      ,[Service_Location]
      ,[Total_Infusion_Time]
      ,[delete_ind]
      ,[Created_By_Name]
      ,[LMP_Notes]
      ,[Addl_Narrative_Notes]
      ,[Discharge_Letter_Text]
      ,[Discharge_Letter_Action]
      ,[Discharge_Letter_User]
      ,[Ivstart_Injection_Site]
      ,[Inventory_Interface]
      ,[Ivstart_Injection_Site2]
      ,[Ivstart_Injection_Site3]
      ,[Premeds_Declined]
      ,[Chair_Time]
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT [enterprise_id]
      ,[practice_id]
      ,[person_id]
      ,[enc_id]
      ,[created_by]
      ,[create_timestamp]
      ,[modified_by]
      ,[modify_timestamp]
      ,[create_timestamp_tz]
      ,[modify_timestamp_tz]
      ,[row_timestamp]
      ,[Diagnosis1_Code]
      ,[Diagnosis1_Description]
      ,[Diagnosis2_Code]
      ,[Diagnosis2_Description]
      ,[Diagnosis3_Code]
      ,[Diagnosis3_Description]
      ,[Discharge_BP]
      ,[Discharge_HR]
      ,[Discharge_Instn_Given]
      ,[Discharge_Instructions]
      ,[Discharge_Pain]
      ,[Discharge_RR]
      ,[Discharge_SpO2]
      ,[Discharge_Temp]
      ,[Discharge_Vitals_Time]
      ,[Final_Sign_Date]
      ,[Final_Sign_InvBillingError]
      ,[Final_Sign_InvBillingUpdate]
      ,[Final_Sign_Time]
      ,[Final_Signed_By]
      ,[Internal_Provider_id]
      ,[Internal_Provider_Name]
      ,[Ivstart_Access]
      ,[Ivstart_Central_Line]
      ,[Ivstart_Lumen_Count]
      ,[Ivstart_Midline_Type]
      ,[Ivstart_OtherAccess]
      ,[Ivstart_PICC_ArmCircum]
      ,[Ivstart_PICC_Pulled]
      ,[Ivstart_PICC_Type]
      ,[Ivstart_PIV]
      ,[Ivstart_PIV_Attempts]
      ,[Ivstart_PIV_Location]
      ,[Ivstart_PIV_Vein]
      ,[Ivstart_PORT_AccessedToday]
      ,[Ivstart_PORT_Type]
      ,[LMP_NA]
      ,[Location_id]
      ,[Med_Provided]
      ,[No_Medications]
      ,[Order_Description]
      ,[Order_seq_no]
      ,[Ordering_Provider_id]
      ,[Ordering_Provider_Name]
      ,[Partial_Sign_Date]
      ,[Partial_Sign_Time]
      ,[Partial_Signed_By]
      ,[Patient_Wt_Kg]
      ,[Patient_Wt_lbs]
      ,[pe_Accompanied_by]
      ,[pe_Ambulatory]
      ,[pe_Cardio_Comments]
      ,[pe_Cardio_Edema]
      ,[pe_Cardio_HRR]
      ,[pe_Distress]
      ,[pe_Distress_Comments]
      ,[pe_Gastro_ABDSoft]
      ,[pe_Gastro_BSounds]
      ,[pe_Gastro_Comments]
      ,[pe_Gastro_Tender]
      ,[pe_IVSite_CleanDry]
      ,[pe_IVSite_Comments]
      ,[pe_IVSite_Pain]
      ,[pe_IVSite_Redness]
      ,[pe_IVSite_SSInfection]
      ,[pe_Neuro_Comments]
      ,[pe_Neuro_Normal]
      ,[pe_Neuro_Pain]
      ,[pe_Neuro_PERRLA]
      ,[pe_Oriented]
      ,[pe_Oriented_Comments]
      ,[pe_Other_Comments]
      ,[pe_Pulmonary_Comments]
      ,[pe_Pulmonary_DecreasedBS]
      ,[pe_Pulmonary_LungsClear]
      ,[pe_Pulmonary_SOB]
      ,[pe_Pulmonary_Wheezes]
      ,[pe_Skin_Color]
      ,[pe_Skin_Comments]
      ,[pe_Skin_OralMuscosa]
      ,[pe_Skin_Turgor]
      ,[pe_Skin_WarmDry_Cool]
      ,[pre_Chest_Xray]
      ,[pre_EpiPen]
      ,[pre_EpiPen_Expiry]
      ,[pre_EpiPen_Guide]
      ,[pre_HepB]
      ,[pre_TB_Test]
      ,[PRN_Sign_Date]
      ,[PRN_Sign_Time]
      ,[PRN_Signed_By]
      ,[PRNMeds]
      ,[Service_Location]
      ,[Total_Infusion_Time]
      ,[delete_ind]
      ,[Created_By_Name]
      ,[LMP_Notes]
      ,[Addl_Narrative_Notes]
      ,[Discharge_Letter_Text]
      ,[Discharge_Letter_Action]
      ,[Discharge_Letter_User]
      ,[Ivstart_Injection_Site]
      ,[Inventory_Interface]
      ,[Ivstart_Injection_Site2]
      ,[Ivstart_Injection_Site3]
      ,[Premeds_Declined]
      ,[Chair_Time]
      ,@DateTime AS [EffectiveDate]
      ,NULL AS [ExpirationDate]
      ,1 AS [CurrentRowFlag]
      ,0 AS [DeleteRowFlag]
      ,@DateTime AS [InsertDate]
    FROM [stage].[NG_PIVC_Infusion_] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_PIVC_Infusion_] AS [t]
        WHERE [t].[enc_id] = [s].[enc_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;