CREATE PROCEDURE [ods].[uspODSCPR_TICKCIUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[CPR_TICKCI]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[CPR_TICKCI] [t]
        INNER JOIN [stage].[CPR_TICKCI] [s]
            ON [t].[TICKNO] = [s].[TICKNO]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[CPR_TICKCI]
    (
    	[TICKNO]
      ,[MRN]
      ,[CONFIRMED]
      ,[ASSIGNED]
      ,[BILLNO]
      ,[START]
      ,[STOP]
      ,[DELIVDATE]
      ,[CONFDATE]
      ,[RXCODE]
      ,[RXMSG]
      ,[RXNUM]
      ,[KITNAME]
      ,[SH_NAME]
      ,[SH_ATTN]
      ,[SH_ADDR]
      ,[SH_CITY]
      ,[SH_STATE]
      ,[SH_ZIP]
      ,[SH_PHONE]
      ,[BI_NAME]
      ,[BI_ATTN]
      ,[BI_ADDR]
      ,[BI_CITY]
      ,[BI_STATE]
      ,[BI_ZIP]
      ,[BI_PHONE]
      ,[LAST_NAME]
      ,[FIRST_NAME]
      ,[PAYOR]
      ,[PICKUP]
      ,[TOTCOST]
      ,[TOTPRICE]
      ,[TOTBPRICE]
      ,[CHOLDERNM]
      ,[CHOLDERADR]
      ,[CHOLDERTYP]
      ,[CBILLTYPE]
      ,[RPTMSG]
      ,[STATUSPTR]
      ,[DELIVINS]
      ,[ENCOUNTER]
      ,[ENT_BY]
      ,[SH_TYPE]
      ,[SH_METHOD]
      ,[COPAY]
      ,[SH_SVCTYPE]
      ,[SH_PACKAGE]
      ,[INSNO]
      ,[SITENO]
      ,[DEFCOLLECT]
      ,[ENC_HOSP]
      ,[PI_NO]
      ,[COMPCODE]
      ,[DRIVER_NO]
      ,[DEPARTDATE]
      ,[SEL]
      ,[DELFLAG]
      ,[TOUCHDATE]
      ,[CHGBYHOST]
      ,[CREATEDON]
      ,[CREATEDBY]
      ,[DTREASON]
      ,[NOOVERRIDE]
      ,[BATCH]
      ,[DTCREATEDBY]
      ,[DTCONFIRMEDBY]
      ,[DTBILLEDBY]
      ,[DTCREATEDDATE]
      ,[DTCONFIRMEDDATE]
      ,[DTBILLEDDATE]
      ,[FIELDCHANGES]
      ,[SIGNATURE]
      ,[PALMUSER]
      ,[RECEIVEDDATE]
      ,[NUMPACKAGES]
      ,[SELECTSN]
      ,[ORIGINALTICKNO]
      ,[CFK_BATCHBILLCLAIMS]
      ,[CFK_REFSOURC]
      ,[TIMEIN]
      ,[TIMEOUT]
      ,[MILEAGE]
      ,[DELIVERED]
      ,[POS]
      ,[CFK_LOCATIONS_DEFAULT]
      ,[PROMDATE]
      ,[VERIFY]
      ,[ORIGINALPDF]
      ,[STAT]
      ,[DP_PROMDATE]
      ,[DP_DELIVEREDTIME]
      ,[SIGNFORPATIENT_NAME]
      ,[SIGNFORPATIENT_RELAT]
      ,[DIRECTSHIP_REF]
      ,[CFK_SUPPLIER]
      ,[CFK_SVCTYPE]
      ,[DIRECTSHIP_MSD]
      ,[DP_PROMDATE_START]
      ,[CFK_TICKCI_ORIG]
      ,[signforpatient_reas]
      ,[onetimeinstruction]
      ,[attempteddel]
      ,[onetimeinstrucflag]
      ,[sh_latitude]
      ,[sh_longitude]
      ,[attemptedstatus]
      ,[cfk_billingreviewstat]
      ,[billingreviewlist]
      ,[billingreviewcomplete]
      ,[cfk_pnnames_completedbillingreview]
      ,[deliverymanagerstatus]
      ,[deliverymanagerservicelevel]
      ,[manuallysplit]
      ,[EffectiveDate]
      ,[ExpirationDate]
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT 	
    	[TICKNO]
      ,[MRN]
      ,[CONFIRMED]
      ,[ASSIGNED]
      ,[BILLNO]
      ,[START]
      ,[STOP]
      ,[DELIVDATE]
      ,[CONFDATE]
      ,[RXCODE]
      ,[RXMSG]
      ,[RXNUM]
      ,[KITNAME]
      ,[SH_NAME]
      ,[SH_ATTN]
      ,[SH_ADDR]
      ,[SH_CITY]
      ,[SH_STATE]
      ,[SH_ZIP]
      ,[SH_PHONE]
      ,[BI_NAME]
      ,[BI_ATTN]
      ,[BI_ADDR]
      ,[BI_CITY]
      ,[BI_STATE]
      ,[BI_ZIP]
      ,[BI_PHONE]
      ,[LAST_NAME]
      ,[FIRST_NAME]
      ,[PAYOR]
      ,[PICKUP]
      ,[TOTCOST]
      ,[TOTPRICE]
      ,[TOTBPRICE]
      ,[CHOLDERNM]
      ,[CHOLDERADR]
      ,[CHOLDERTYP]
      ,[CBILLTYPE]
      ,[RPTMSG]
      ,[STATUSPTR]
      ,[DELIVINS]
      ,[ENCOUNTER]
      ,[ENT_BY]
      ,[SH_TYPE]
      ,[SH_METHOD]
      ,[COPAY]
      ,[SH_SVCTYPE]
      ,[SH_PACKAGE]
      ,[INSNO]
      ,[SITENO]
      ,[DEFCOLLECT]
      ,[ENC_HOSP]
      ,[PI_NO]
      ,[COMPCODE]
      ,[DRIVER_NO]
      ,[DEPARTDATE]
      ,[SEL]
      ,[DELFLAG]
      ,[TOUCHDATE]
      ,[CHGBYHOST]
      ,[CREATEDON]
      ,[CREATEDBY]
      ,[DTREASON]
      ,[NOOVERRIDE]
      ,[BATCH]
      ,[DTCREATEDBY]
      ,[DTCONFIRMEDBY]
      ,[DTBILLEDBY]
      ,[DTCREATEDDATE]
      ,[DTCONFIRMEDDATE]
      ,[DTBILLEDDATE]
      ,[FIELDCHANGES]
      ,[SIGNATURE]
      ,[PALMUSER]
      ,[RECEIVEDDATE]
      ,[NUMPACKAGES]
      ,[SELECTSN]
      ,[ORIGINALTICKNO]
      ,[CFK_BATCHBILLCLAIMS]
      ,[CFK_REFSOURC]
      ,[TIMEIN]
      ,[TIMEOUT]
      ,[MILEAGE]
      ,[DELIVERED]
      ,[POS]
      ,[CFK_LOCATIONS_DEFAULT]
      ,[PROMDATE]
      ,[VERIFY]
      ,[ORIGINALPDF]
      ,[STAT]
      ,[DP_PROMDATE]
      ,[DP_DELIVEREDTIME]
      ,[SIGNFORPATIENT_NAME]
      ,[SIGNFORPATIENT_RELAT]
      ,[DIRECTSHIP_REF]
      ,[CFK_SUPPLIER]
      ,[CFK_SVCTYPE]
      ,[DIRECTSHIP_MSD]
      ,[DP_PROMDATE_START]
      ,[CFK_TICKCI_ORIG]
      ,[signforpatient_reas]
      ,[onetimeinstruction]
      ,[attempteddel]
      ,[onetimeinstrucflag]
      ,[sh_latitude]
      ,[sh_longitude]
      ,[attemptedstatus]
      ,[cfk_billingreviewstat]
      ,[billingreviewlist]
      ,[billingreviewcomplete]
      ,[cfk_pnnames_completedbillingreview]
      ,[deliverymanagerstatus]
      ,[deliverymanagerservicelevel]
      ,[manuallysplit]
      ,  @DateTime AS [EffectiveDate]
      ,  NULL AS [ExpirationDate]
      ,  1 AS [CurrentRowFlag]
      ,  0 AS [DeleteRowFlag]
      ,  @DateTime AS [InsertDate]
    FROM [stage].[CPR_TICKCI] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[CPR_TICKCI] AS [t]
        WHERE [t].[TICKNO] = [s].[TICKNO]
              AND [t].[CurrentRowFlag] = 1
    );

END;

