CREATE PROCEDURE [ods].[uspODSNG_person_payerUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_person_payer]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_person_payer] [t]
        INNER JOIN [stage].[NG_person_payer] [s]
            ON [t].[person_payer_id] = [s].[person_payer_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_person_payer]
    ([person_id]
      ,[payer_id]
      ,[person_payer_id]
      ,[bc_plan_code]
      ,[active_ind]
      ,[copay_amt]
      ,[deductible_amt]
      ,[copay_type]
      ,[copay_percent]
      ,[policy_eff_date]
      ,[policy_exp_date]
      ,[policy_nbr]
      ,[plan_nbr]
      ,[notify_ind]
      ,[verify_ind]
      ,[precert_ind]
      ,[group_name]
      ,[group_nbr]
      ,[contact_last_name]
      ,[contact_first_name]
      ,[contact_middle_name]
      ,[contact_phone]
      ,[contact_phone_ext]
      ,[contact_fax]
      ,[msp_reason]
      ,[medigap_id_nbr]
      ,[sig_source]
      ,[payer_name]
      ,[mstr_payer_name]
      ,[medical_cov_ind]
      ,[dental_cov_ind]
      ,[prescription_cov_ind]
      ,[eye_cov_ind]
      ,[workmens_comp_cov_ind]
      ,[def_cob]
      ,[employer_id]
      ,[kenpak_maid]
      ,[kenpak_ind]
      ,[default_payer_date]
      ,[ndex_county]
      ,[address_line_1]
      ,[address_line_2]
      ,[city]
      ,[state]
      ,[zip]
      ,[country_id]
      ,[county_id]
      ,[delete_ind]
      ,[email_address]
      ,[claim_type]
      ,[ins_type]
      ,[last_elig_check]
      ,[new_emp_ins_ind]
      ,[legacy_copay_tos_1]
      ,[legacy_copay_tos_1_amount]
      ,[legacy_copay_tos_2]
      ,[legacy_copay_tos_2_amount]
      ,[legacy_copay_tos_3]
      ,[legacy_copay_tos_3_amount]
      ,[note]
      ,[create_timestamp]
      ,[created_by]
      ,[modified_by]
      ,[modify_timestamp]
      ,[row_timestamp]
      ,[ins_card_first_name]
      ,[ins_card_middle_name]
      ,[ins_card_last_name]
      ,[ins_card_suffix]
      ,[tpl_code]
      ,[referral_ind]
      ,[refund_address_line1]
      ,[refund_address_line2]
      ,[refund_city]
      ,[refund_state]
      ,[refund_zip]
      ,[refund_country_id]
      ,[refund_county_id]
      ,[override_date_of_birth]
      ,[rts_override]
      ,[override_sex] 
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT [person_id]
      ,[payer_id]
      ,[person_payer_id]
      ,[bc_plan_code]
      ,[active_ind]
      ,[copay_amt]
      ,[deductible_amt]
      ,[copay_type]
      ,[copay_percent]
      ,[policy_eff_date]
      ,[policy_exp_date]
      ,[policy_nbr]
      ,[plan_nbr]
      ,[notify_ind]
      ,[verify_ind]
      ,[precert_ind]
      ,[group_name]
      ,[group_nbr]
      ,[contact_last_name]
      ,[contact_first_name]
      ,[contact_middle_name]
      ,[contact_phone]
      ,[contact_phone_ext]
      ,[contact_fax]
      ,[msp_reason]
      ,[medigap_id_nbr]
      ,[sig_source]
      ,[payer_name]
      ,[mstr_payer_name]
      ,[medical_cov_ind]
      ,[dental_cov_ind]
      ,[prescription_cov_ind]
      ,[eye_cov_ind]
      ,[workmens_comp_cov_ind]
      ,[def_cob]
      ,[employer_id]
      ,[kenpak_maid]
      ,[kenpak_ind]
      ,[default_payer_date]
      ,[ndex_county]
      ,[address_line_1]
      ,[address_line_2]
      ,[city]
      ,[state]
      ,[zip]
      ,[country_id]
      ,[county_id]
      ,[delete_ind]
      ,[email_address]
      ,[claim_type]
      ,[ins_type]
      ,[last_elig_check]
      ,[new_emp_ins_ind]
      ,[legacy_copay_tos_1]
      ,[legacy_copay_tos_1_amount]
      ,[legacy_copay_tos_2]
      ,[legacy_copay_tos_2_amount]
      ,[legacy_copay_tos_3]
      ,[legacy_copay_tos_3_amount]
      ,[note]
      ,[create_timestamp]
      ,[created_by]
      ,[modified_by]
      ,[modify_timestamp]
      ,[row_timestamp]
      ,[ins_card_first_name]
      ,[ins_card_middle_name]
      ,[ins_card_last_name]
      ,[ins_card_suffix]
      ,[tpl_code]
      ,[referral_ind]
      ,[refund_address_line1]
      ,[refund_address_line2]
      ,[refund_city]
      ,[refund_state]
      ,[refund_zip]
      ,[refund_country_id]
      ,[refund_county_id]
      ,[override_date_of_birth]
      ,[rts_override]
      ,[override_sex] 
      ,@DateTime AS [EffectiveDate]
      ,NULL AS [ExpirationDate]
      ,1 AS [CurrentRowFlag]
      ,0 AS [DeleteRowFlag]
      ,@DateTime AS [InsertDate]
    FROM [stage].[NG_person_payer] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_person_payer] AS [t]
        WHERE [t].[person_payer_id] = [s].[person_payer_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;