CREATE PROCEDURE [ods].[uspODSNG_accountsUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_accounts]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_accounts] [t]
        INNER JOIN [stage].[NG_accounts] [s]
            ON [t].[acct_id] = [s].[acct_id]
            AND [t].[practice_id]=[s].[practice_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_accounts]
    ( [enterprise_id]
      ,[practice_id]
      ,[site_id]
      ,[acct_id]
      ,[acct_nbr]
      ,[guar_id]
      ,[guar_type]
      ,[print_stmt_ind]
      ,[print_invoice_ind]
      ,[last_stmt_date]
      ,[last_letter_date]
      ,[last_budget_letter_date]
      ,[last_invoice_date]
      ,[budget_enabled_ind]
      ,[budget_date]
      ,[budget_due_date]
      ,[budget_cycle]
      ,[budget_num_payments]
      ,[budget_payment_amt]
      ,[budget_total]
      ,[budget_delinquent_date]
      ,[budget_termination_date]
      ,[stmt_day_of_month]
      ,[budget_day_of_month]
      ,[invoice_day_of_month]
      ,[status]
      ,[next_stmt_date]
      ,[next_invoice_date]
      ,[force_stmt_ind]
      ,[credit_rating]
      ,[last_self_pay_date]
      ,[suppress_dunning_msg_ind]
      ,[last_print_stmt_date]
      ,[create_timestamp]
      ,[created_by]
      ,[modify_timestamp]
      ,[modified_by]
      ,[row_timestamp]
      ,[outsource_exempt_ind]
      ,[statement_counter]
      ,[send_coll_letter_ind]
      ,[collection_letter_id]
      ,[last_nxmd_stmt_date]
      ,[last_pat_pay_amt]
      ,[last_pat_pay_date]
      ,[last_bad_debt_pay_amt]
      ,[last_bad_debt_pay_date]
      ,[last_consent_form_id]
      ,[last_consent_print_by]
      ,[last_consent_print_date]
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT [enterprise_id]
      ,[practice_id]
      ,[site_id]
      ,[acct_id]
      ,[acct_nbr]
      ,[guar_id]
      ,[guar_type]
      ,[print_stmt_ind]
      ,[print_invoice_ind]
      ,[last_stmt_date]
      ,[last_letter_date]
      ,[last_budget_letter_date]
      ,[last_invoice_date]
      ,[budget_enabled_ind]
      ,[budget_date]
      ,[budget_due_date]
      ,[budget_cycle]
      ,[budget_num_payments]
      ,[budget_payment_amt]
      ,[budget_total]
      ,[budget_delinquent_date]
      ,[budget_termination_date]
      ,[stmt_day_of_month]
      ,[budget_day_of_month]
      ,[invoice_day_of_month]
      ,[status]
      ,[next_stmt_date]
      ,[next_invoice_date]
      ,[force_stmt_ind]
      ,[credit_rating]
      ,[last_self_pay_date]
      ,[suppress_dunning_msg_ind]
      ,[last_print_stmt_date]
      ,[create_timestamp]
      ,[created_by]
      ,[modify_timestamp]
      ,[modified_by]
      ,[row_timestamp]
      ,[outsource_exempt_ind]
      ,[statement_counter]
      ,[send_coll_letter_ind]
      ,[collection_letter_id]
      ,[last_nxmd_stmt_date]
      ,[last_pat_pay_amt]
      ,[last_pat_pay_date]
      ,[last_bad_debt_pay_amt]
      ,[last_bad_debt_pay_date]
      ,[last_consent_form_id]
      ,[last_consent_print_by]
      ,[last_consent_print_date]
      ,@DateTime AS [EffectiveDate]
      ,NULL AS [ExpirationDate]
      ,1 AS [CurrentRowFlag]
      ,0 AS [DeleteRowFlag]
      ,@DateTime AS [InsertDate]
    FROM [stage].[NG_accounts] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_accounts] AS [t]
        WHERE [t].[acct_id] = [s].[acct_id]
            AND [t].[practice_id]=[s].[practice_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;