CREATE PROCEDURE [ods].[uspODSNG_transactionsUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_transactions]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_transactions] [t]
        INNER JOIN [stage].[NG_transactions] [s]
            ON [t].[trans_id] = [s].[trans_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_transactions]
    ( [trans_id]
      ,[practice_id]
      ,[source_id]
      ,[source_type]
      ,[batch_nbr]
      ,[batch_date]
      ,[batch_item_nbr]
      ,[person_id]
      ,[insured_person_id]
      ,[payer_id]
      ,[tran_date]
      ,[type]
      ,[tran_amt]
      ,[tran_code_id]
      ,[billed_amt]
      ,[approved_amt]
      ,[source]
      ,[post_ind]
      ,[post_date]
      ,[tracking_desc_40]
      ,[transfer_id]
      ,[transfer_type]
      ,[link_id]
      ,[closing_date]
      ,[override_closing_date]
      ,[reason_codes_display_only]
      ,[person_payer_id]
      ,[alt_payer_ind]
      ,[alt_req_both_payments_id]
      ,[create_timestamp]
      ,[created_by]
      ,[modify_timestamp]
      ,[modified_by]
      ,[row_timestamp]
      ,[era_post_ind]
      ,[resubmission_reference_nbr]
      ,[reversal_trans_id]
      ,[clm_lvl_remarks]
      ,[transaction_notes]
      ,[disc_reversal_ind]
      ,[disc_spread_type]
      ,[disc_spread_percent]
      ,[refund_address_line1]
      ,[refund_address_line2]
      ,[refund_city]
      ,[refund_state]
      ,[refund_zip]
      ,[refund_country_id]
      ,[refund_county_id]
      ,[disc_level]
      ,[parent_batch_nbr]
      ,[parent_batch_date]
      ,[reconciled_ind]
      ,[external_id1]
      ,[external_id2]
      ,[refund_to_name]
      ,[refund_pat_type]
      ,[apc_ind]
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT [trans_id]
      ,[practice_id]
      ,[source_id]
      ,[source_type]
      ,[batch_nbr]
      ,[batch_date]
      ,[batch_item_nbr]
      ,[person_id]
      ,[insured_person_id]
      ,[payer_id]
      ,[tran_date]
      ,[type]
      ,[tran_amt]
      ,[tran_code_id]
      ,[billed_amt]
      ,[approved_amt]
      ,[source]
      ,[post_ind]
      ,[post_date]
      ,[tracking_desc_40]
      ,[transfer_id]
      ,[transfer_type]
      ,[link_id]
      ,[closing_date]
      ,[override_closing_date]
      ,[reason_codes_display_only]
      ,[person_payer_id]
      ,[alt_payer_ind]
      ,[alt_req_both_payments_id]
      ,[create_timestamp]
      ,[created_by]
      ,[modify_timestamp]
      ,[modified_by]
      ,[row_timestamp]
      ,[era_post_ind]
      ,[resubmission_reference_nbr]
      ,[reversal_trans_id]
      ,[clm_lvl_remarks]
      ,[transaction_notes]
      ,[disc_reversal_ind]
      ,[disc_spread_type]
      ,[disc_spread_percent]
      ,[refund_address_line1]
      ,[refund_address_line2]
      ,[refund_city]
      ,[refund_state]
      ,[refund_zip]
      ,[refund_country_id]
      ,[refund_county_id]
      ,[disc_level]
      ,[parent_batch_nbr]
      ,[parent_batch_date]
      ,[reconciled_ind]
      ,[external_id1]
      ,[external_id2]
      ,[refund_to_name]
      ,[refund_pat_type]
      ,[apc_ind]
      ,@DateTime AS [EffectiveDate]
      ,NULL AS [ExpirationDate]
      ,1 AS [CurrentRowFlag]
      ,0 AS [DeleteRowFlag]
      ,@DateTime AS [InsertDate]
    FROM [stage].[NG_transactions] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_transactions] AS [t]
        WHERE [t].[trans_id] = [s].[trans_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;