CREATE PROCEDURE [ods].[uspODSNG_patientUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_patient]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_patient] [t]
        INNER JOIN [stage].[NG_patient] [s]
            ON [t].[person_id] = [s].[person_id]
            AND [t].[practice_id]=[s].[practice_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_patient]
    ( [enterprise_id]
      ,[practice_id]
      ,[person_id]
      ,[first_office_enc_date]
      ,[last_office_enc_date]
      ,[next_office_enc_date]
      ,[pharmacy_code_1_id]
      ,[pharmacy_code_2_id]
      ,[default_location_id]
      ,[privacy_level]
      ,[suppress_billing_ind]
      ,[preferred_provider_id]
      ,[financial_class]
      ,[site_id]
      ,[med_rec_nbr]
      ,[guar_id]
      ,[guar_type]
      ,[contact_person_id]
      ,[user_defined1]
      ,[user_defined2]
      ,[user_defined3]
      ,[user_defined4]
      ,[print_stmt_ind]
      ,[last_letter_date]
      ,[rendering_prov_id]
      ,[co_managed_ind]
      ,[co_managed_prov_id]
      ,[mrkt_plan_id]
      ,[mrkt_source_id]
      ,[mrkt_source_type]
      ,[mrkt_comments]
      ,[referring_prov_id]
      ,[last_print_statement_date]
      ,[privacy_notice_code_id]
      ,[privacy_notice_issued]
      ,[privacy_notice_received]
      ,[nxmd_enrollment]
      ,[privacy_notice_notes]
      ,[created_by]
      ,[create_timestamp]
      ,[modified_by]
      ,[modify_timestamp]
      ,[row_timestamp]
      ,[outsource_exempt_ind]
      ,[mrkt_details]
      ,[user_defined5]
      ,[user_defined6]
      ,[user_defined7]
      ,[user_defined8]
      ,[head_of_household_id]
      ,[create_timestamp_tz]
      ,[modify_timestamp_tz]
      ,[no_unresolved_allergies_ind]
      ,[no_active_medications_ind]
      ,[no_active_problems]
      ,[pm_ind]
      ,[pharmacy_code_mo_id]
      ,[no_active_problems_snomed]
      ,[no_known_imm_history_ind]
      ,[no_known_procedures_ind]
      ,[no_active_devices_ind]
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT [enterprise_id]
      ,[practice_id]
      ,[person_id]
      ,[first_office_enc_date]
      ,[last_office_enc_date]
      ,[next_office_enc_date]
      ,[pharmacy_code_1_id]
      ,[pharmacy_code_2_id]
      ,[default_location_id]
      ,[privacy_level]
      ,[suppress_billing_ind]
      ,[preferred_provider_id]
      ,[financial_class]
      ,[site_id]
      ,[med_rec_nbr]
      ,[guar_id]
      ,[guar_type]
      ,[contact_person_id]
      ,[user_defined1]
      ,[user_defined2]
      ,[user_defined3]
      ,[user_defined4]
      ,[print_stmt_ind]
      ,[last_letter_date]
      ,[rendering_prov_id]
      ,[co_managed_ind]
      ,[co_managed_prov_id]
      ,[mrkt_plan_id]
      ,[mrkt_source_id]
      ,[mrkt_source_type]
      ,[mrkt_comments]
      ,[referring_prov_id]
      ,[last_print_statement_date]
      ,[privacy_notice_code_id]
      ,[privacy_notice_issued]
      ,[privacy_notice_received]
      ,[nxmd_enrollment]
      ,[privacy_notice_notes]
      ,[created_by]
      ,[create_timestamp]
      ,[modified_by]
      ,[modify_timestamp]
      ,[row_timestamp]
      ,[outsource_exempt_ind]
      ,[mrkt_details]
      ,[user_defined5]
      ,[user_defined6]
      ,[user_defined7]
      ,[user_defined8]
      ,[head_of_household_id]
      ,[create_timestamp_tz]
      ,[modify_timestamp_tz]
      ,[no_unresolved_allergies_ind]
      ,[no_active_medications_ind]
      ,[no_active_problems]
      ,[pm_ind]
      ,[pharmacy_code_mo_id]
      ,[no_active_problems_snomed]
      ,[no_known_imm_history_ind]
      ,[no_known_procedures_ind]
      ,[no_active_devices_ind]
      ,@DateTime AS [EffectiveDate]
      ,NULL AS [ExpirationDate]
      ,1 AS [CurrentRowFlag]
      ,0 AS [DeleteRowFlag]
      ,@DateTime AS [InsertDate]
    FROM [stage].[NG_patient] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_patient] AS [t]
        WHERE [t].[person_id] = [s].[person_id]
            AND [t].[practice_id]=[s].[practice_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;