CREATE PROCEDURE [ods].[uspODSNG_location_mstrUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_location_mstr]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_location_mstr] [t]
        INNER JOIN [stage].[NG_location_mstr] [s]
            ON [t].[location_id] = [s].[location_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_location_mstr]
    (
 	    [location_id]
      ,[location_type]
      ,[location_name]
      ,[address_line_1]
      ,[address_line_2]
      ,[city]
      ,[state]
      ,[zip]
      ,[county_id]
      ,[country_id]
      ,[phone]
      ,[contact_last_name]
      ,[contact_first_name]
      ,[contact_initial]
      ,[extension]
      ,[alternate_phone]
      ,[mammo_cert_nbr]
      ,[site_id]
      ,[color_code]
      ,[clia_id]
      ,[external_id]
      ,[service_item_lib_id]
      ,[sim_exception_id]
      ,[ub92_bill_ind]
      ,[ub92_grace_period]
      ,[location_subgrouping1_id]
      ,[location_subgrouping2_id]
      ,[dme_provider_nbr]
      ,[alt_phone_ext]
      ,[alt_phone_desc]
      ,[fax]
      ,[internal_location_ind]
      ,[dial_area_code]
      ,[fax_extras]
      ,[bc_bs_fac_id_nbr]
      ,[hcfa_box32_ind]
      ,[caid_fac_id_nbr]
      ,[fac_entity_id]
      ,[care_fac_id_nbr]
      ,[location_schedulable_ind]
      ,[facility_location_ind]
      ,[note]
      ,[delete_ind]
      ,[create_timestamp]
      ,[created_by]
      ,[modify_timestamp]
      ,[modified_by]
      ,[row_timestamp]
      ,[search_ahead_ind]
      ,[ud_directions]
      ,[optical_location_ind]
      ,[national_provider_id]
      ,[visionweb_username]
      ,[visionweb_password]
      ,[image_id]
      ,[dme_national_provider_id]
      ,[taxonomy_id]
      ,[place_of_service]
      ,[loc_tax_id]
      ,[suppress_rendering_code]
      ,[tax_rate_library_id]
      ,[et_swipe_mid]
      ,[et_non_swipe_mid]
      ,[et_terminal_id]
      ,[et_store_id]
      ,[et_merchant_id]
      ,[et_regkey_id]
      ,[facility_visit_type]
      ,[healthcare_svc_location_code]
      ,[crosswalk_charge_entry_ind]
      ,[crosswalk_order]
      ,[require_surg_proc_cd_ind]
      ,[hos_billing_ind]
      ,[hos_location_ind]
      ,[et_txp_merchant_id]
      ,[et_txp_regkey_id]
      ,[et_txp_hosted_key]
      ,[vsp_vendor_id]
      ,[vsp_vendor_password]
      ,[vsp_username]
      ,[vsp_password]
      ,[vsp_office_id]
      ,[med_dev_tax_ind]
      ,[tax_gross_amount_ind]
      ,[opk_provider_type]
      ,[ccbhc_location_ind]
      ,[address_valid_ind]
      ,[EffectiveDate]
      ,[ExpirationDate]        
      ,[CurrentRowFlag]
      ,[DeleteRowFlag]
      ,[InsertDate]
    )
    SELECT 	[location_id]
          ,[location_type]
          ,[location_name]
          ,[address_line_1]
          ,[address_line_2]
          ,[city]
          ,[state]
          ,[zip]
          ,[county_id]
          ,[country_id]
          ,[phone]
          ,[contact_last_name]
          ,[contact_first_name]
          ,[contact_initial]
          ,[extension]
          ,[alternate_phone]
          ,[mammo_cert_nbr]
          ,[site_id]
          ,[color_code]
          ,[clia_id]
          ,[external_id]
          ,[service_item_lib_id]
          ,[sim_exception_id]
          ,[ub92_bill_ind]
          ,[ub92_grace_period]
          ,[location_subgrouping1_id]
          ,[location_subgrouping2_id]
          ,[dme_provider_nbr]
          ,[alt_phone_ext]
          ,[alt_phone_desc]
          ,[fax]
          ,[internal_location_ind]
          ,[dial_area_code]
          ,[fax_extras]
          ,[bc_bs_fac_id_nbr]
          ,[hcfa_box32_ind]
          ,[caid_fac_id_nbr]
          ,[fac_entity_id]
          ,[care_fac_id_nbr]
          ,[location_schedulable_ind]
          ,[facility_location_ind]
          ,[note]
          ,[delete_ind]
          ,[create_timestamp]
          ,[created_by]
          ,[modify_timestamp]
          ,[modified_by]
          ,[row_timestamp]
          ,[search_ahead_ind]
          ,[ud_directions]
          ,[optical_location_ind]
          ,[national_provider_id]
          ,[visionweb_username]
          ,[visionweb_password]
          ,[image_id]
          ,[dme_national_provider_id]
          ,[taxonomy_id]
          ,[place_of_service]
          ,[loc_tax_id]
          ,[suppress_rendering_code]
          ,[tax_rate_library_id]
          ,[et_swipe_mid]
          ,[et_non_swipe_mid]
          ,[et_terminal_id]
          ,[et_store_id]
          ,[et_merchant_id]
          ,[et_regkey_id]
          ,[facility_visit_type]
          ,[healthcare_svc_location_code]
          ,[crosswalk_charge_entry_ind]
          ,[crosswalk_order]
          ,[require_surg_proc_cd_ind]
          ,[hos_billing_ind]
          ,[hos_location_ind]
          ,[et_txp_merchant_id]
          ,[et_txp_regkey_id]
          ,[et_txp_hosted_key]
          ,[vsp_vendor_id]
          ,[vsp_vendor_password]
          ,[vsp_username]
          ,[vsp_password]
          ,[vsp_office_id]
          ,[med_dev_tax_ind]
          ,[tax_gross_amount_ind]
          ,[opk_provider_type]
          ,[ccbhc_location_ind]
          ,[address_valid_ind]
          ,  @DateTime AS [EffectiveDate]
          , NULL AS [ExpirationDate]
          , 1 AS [CurrentRowFlag]
          , 0 AS [DeleteRowFlag]
          , @DateTime AS [InsertDate]
    FROM [stage].[NG_location_mstr] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_location_mstr] AS [t]
        WHERE [t].[location_id] = [s].[location_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;