CREATE PROCEDURE [ods].[uspODSNG_provider_mstrUpsert]
AS
BEGIN
    SET NOCOUNT ON;
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DECLARE @DateTime DATETIME = GETDATE();

    -- Update existing records to previous version
    UPDATE [ods].[NG_provider_mstr]
    SET [CurrentRowFlag] = 0,
        [ExpirationDate] = @DateTime,
        [UpdateDate] = @DateTime
    FROM [ods].[NG_provider_mstr] [t]
        INNER JOIN [stage].[NG_provider_mstr] [s]
            ON [t].[provider_id] = [s].[provider_id]
               AND [t].[CurrentRowFlag] = 1;

    SET @DateTime = DATEADD(SS, 1, @DateTime);

    -- Insert New and modified records as current version
    INSERT INTO [ods].[NG_provider_mstr]
    (
        [provider_id],
        [description],
        [last_name],
        [first_name],
        [middle_name],
        [address_line_1],
        [address_line_2],
        [city],
        [state],
        [zip],
        [country_id],
        [county_id],
        [phone],
        [home_phone],
        [home_fax],
        [delete_ind],
        [external_id],
        [email_address],
        [mcs_referto_ind],
        [provider_subgrouping1_id],
        [provider_subgrouping2_id],
        [show_notes_on_appt_ind],
        [note],
        [provider_type_referring_ind],
        [provider_type_pcp_ind],
        [provider_type_admitting_ind],
        [degree],
        [ssn],
        [specialty_code_1],
        [specialty_code_2],
        [other_lic_id],
        [other_lic_desc],
        [primary_loc_id],
        [employer_id],
        [language1_id],
        [language2_id],
        [language3_id],
        [export_service_ind],
        [pager],
        [salutory_name],
        [spouse_name],
        [letter_code],
        [hosp_affiliations],
        [mobile_phone],
        [home_addr_line_1],
        [home_addr_line_2],
        [home_city],
        [home_state],
        [home_zip],
        [other1_name],
        [other1_addr_line_1],
        [other1_addr_line_2],
        [other1_city],
        [other1_state],
        [other1_zip],
        [other1_phone],
        [other2_name],
        [other2_addr_line_1],
        [other2_addr_line_2],
        [other2_city],
        [other2_state],
        [other2_zip],
        [other2_phone],
        [fax_extras],
        [taxonomy_id],
        [fax],
        [home_county_id],
        [other2_country_id],
        [other2_county_id],
        [other1_country_id],
        [other1_county_id],
        [provider_type_1_consulting_ind],
        [provider_type_2_consulting_ind],
        [phone_ext],
        [home_country_id],
        [legacy_group_member_id],
        [national_provider_id],
        [refer_practice_name],
        [legacy_group_member_nbr],
        [zone1_id],
        [zone2_id],
        [zone3_id],
        [created_by],
        [modified_by],
        [create_timestamp],
        [modify_timestamp],
        [default_tax_id],
        [pqri_edits_ind],
        [provider_type_ordering_ind],
        [business_addr_valid_ind],
        [home_addr_valid_ind],
        [other1_addr_valid_ind],
        [other2_addr_valid_ind],
        [EffectiveDate],
        [ExpirationDate],        
        [CurrentRowFlag],
        [DeleteRowFlag],
        [InsertDate]
    )
    SELECT [provider_id],
           [description],
           [last_name],
           [first_name],
           [middle_name],
           [address_line_1],
           [address_line_2],
           [city],
           [state],
           [zip],
           [country_id],
           [county_id],
           [phone],
           [home_phone],
           [home_fax],
           [delete_ind],
           [external_id],
           [email_address],
           [mcs_referto_ind],
           [provider_subgrouping1_id],
           [provider_subgrouping2_id],
           [show_notes_on_appt_ind],
           [note],
           [provider_type_referring_ind],
           [provider_type_pcp_ind],
           [provider_type_admitting_ind],
           [degree],
           [ssn],
           [specialty_code_1],
           [specialty_code_2],
           [other_lic_id],
           [other_lic_desc],
           [primary_loc_id],
           [employer_id],
           [language1_id],
           [language2_id],
           [language3_id],
           [export_service_ind],
           [pager],
           [salutory_name],
           [spouse_name],
           [letter_code],
           [hosp_affiliations],
           [mobile_phone],
           [home_addr_line_1],
           [home_addr_line_2],
           [home_city],
           [home_state],
           [home_zip],
           [other1_name],
           [other1_addr_line_1],
           [other1_addr_line_2],
           [other1_city],
           [other1_state],
           [other1_zip],
           [other1_phone],
           [other2_name],
           [other2_addr_line_1],
           [other2_addr_line_2],
           [other2_city],
           [other2_state],
           [other2_zip],
           [other2_phone],
           [fax_extras],
           [taxonomy_id],
           [fax],
           [home_county_id],
           [other2_country_id],
           [other2_county_id],
           [other1_country_id],
           [other1_county_id],
           [provider_type_1_consulting_ind],
           [provider_type_2_consulting_ind],
           [phone_ext],
           [home_country_id],
           [legacy_group_member_id],
           [national_provider_id],
           [refer_practice_name],
           [legacy_group_member_nbr],
           [zone1_id],
           [zone2_id],
           [zone3_id],
           [created_by],
           [modified_by],
           [create_timestamp],
           [modify_timestamp],
           [default_tax_id],
           [pqri_edits_ind],
           [provider_type_ordering_ind],
           [business_addr_valid_ind],
           [home_addr_valid_ind],
           [other1_addr_valid_ind],
           [other2_addr_valid_ind],
           @DateTime AS [EffectiveDate],
           NULL AS [ExpirationDate],
           1 AS [CurrentRowFlag],
           0 AS [DeleteRowFlag],
           @DateTime AS [InsertDate]
    FROM [stage].[NG_provider_mstr] AS [s]
    WHERE NOT EXISTS
    (
        SELECT *
        FROM [ods].[NG_provider_mstr] AS [t]
        WHERE [t].[provider_id] = [s].[provider_id]
              AND [t].[CurrentRowFlag] = 1
    );  

END;