CREATE TABLE [stage].[CPR_TICKC](
	[CPK_TICKC] [int] NOT NULL,
	[TICKNO] [int] NULL,
	[NO] [int] NULL,
	[MRN] [varchar](6) NULL,
	[NAME_] [varchar](100) NULL,
	[CODE] [int] NULL,
	[DORMCODE] [varchar](1) NULL,
	[NEXTCODE] [int] NULL,
	[PRN] [varchar](6) NULL,
	[DEFQUANT] [numeric](15, 4) NULL,
	[SAVQUANT] [numeric](15, 4) NULL,
	[RAWQUANT] [numeric](15, 4) NULL,
	[CATTEXT] [varchar](20) NULL,
	[PARTTYPE] [varchar](1) NULL,
	[EXP] [datetime] NULL,
	[RXDAYS] [int] NULL,
	[RXCODE] [varchar](15) NULL,
	[KNUM] [int] NULL,
	[LOTNUM] [varchar](23) NULL,
	[PARTNUM] [varchar](20) NULL,
	[COST] [numeric](15, 4) NULL,
	[PRICE] [numeric](15, 4) NULL,
	[SPRICE] [numeric](15, 4) NULL,
	[BPRICE] [numeric](15, 4) NULL,
	[TOBILL] [varchar](1) NULL,
	[ONDT] [varchar](1) NULL,
	[SUPPLY] [varchar](1) NULL,
	[CHGCODE] [varchar](5) NULL,
	[CDAFLAG] [varchar](1) NULL,
	[CADJUSTRES] [varchar](24) NULL,
	[CDISPOSITN] [varchar](10) NULL,
	[CFREQ] [varchar](3) NULL,
	[LREFILL] [int] NULL,
	[OTNO] [int] NULL,
	[INITS] [varchar](3) NULL,
	[DUMMY] [varchar](1) NULL,
	[FREQUENCY] [varchar](20) NULL,
	[LABLOGNO] [int] NULL,
	[SUPLOCNO] [int] NULL,
	[MAKERR] [varchar](1) NULL,
	[UNITSVIAL] [int] NULL,
	[VIALS] [int] NULL,
	[DELFLAG] [int] NOT NULL,
	[TOUCHDATE] [datetime] NULL,
	[CHGBYHOST] [varchar](100) NULL,
	[CREATEDON] [datetime] NULL,
	[CREATEDBY] [varchar](100) NULL,
	[RAWSPK] [int] NULL,
	[DEDUCTED] [int] NULL,
	[TAXABLE] [varchar](1) NULL,
	[DOCKEY] [int] NULL,
	[DOCTABLE] [varchar](50) NULL,
	[REQAUTH] [int] NULL,
	[CFK_INSVERI] [int] NULL,
	[STOPRR] [int] NULL,
	[FK_POPUPDATA_RENTAL_PRICETYPE] [int] NULL,
	[UOMTEXT] [varchar](50) NULL,
	[UOMEACHES] [numeric](15, 4) NULL,
	[PICKUP] [bit] NULL,
	[EXCHANGEKEY] [int] NULL,
	[SELECTSN] [bit] NULL,
	[SCANPROC] [int] NULL,
	[QUOTEITEM] [bit] NULL,
	[ACCEPTASSIGNMENT] [varchar](1) NULL,
	[EXPECTED] [numeric](15, 4) NULL,
	[PATIENTEA] [numeric](15, 4) NULL,
	[CFK_INSCOMP] [int] NULL,
	[PATIENTPERCENT] [int] NULL,
	[CFK_PATINS] [int] NULL,
	[MCRNOTCOVERED] [bit] NULL,
	[NOTCOVERED] [bit] NULL,
	[CFK_LABELS] [int] NULL,
	[DXCODE] [varchar](6) NULL,
	[NARRATIVE] [varchar](max) NULL,
	[MODIFIER] [varchar](11) NULL,
	[BILLNO] [int] NULL,
	[DIRECTSHIP_PRICE] [numeric](15, 4) NULL,
	[DIRECTSHIP_PRICESOURCE] [varchar](50) NULL,
	[DIRECTSHIP_BACKORDERQTY] [numeric](15, 4) NULL,
	[DIRECTSHIP_AVAILABLE] [bit] NULL,
	[LINENUMBER] [int] NULL,
	[SHIPPEDQTY] [numeric](15, 4) NULL,
	[REORDER] [varchar](100) NULL,
	[ASSISTMEDSENT] [bit] NULL,
	[CFK_CBA_PC] [int] NULL,
	[CBA_KE] [bit] NULL,
	[NEEDUPDATE] [bit] NULL,
	[AUTHOVERRIDE] [bit] NULL,
	[LOANER] [int] NULL,
	[BILLED_TAX] [numeric](19, 4) NULL,
	[EXPECTED_TAX] [numeric](19, 4) NULL,
	[TAXABLE_INT] [int] NULL,
	[CFK_TAXCODES] [int] NULL,
	[disc] [float] NULL,
	[discprice] [float] NULL,
	[retquant] [numeric](15, 4) NULL,
	[fsaeligible] [bit] NULL,
	[isdiscardquantity] [bit] NULL,
	[InsertDate] DATETIME,
 CONSTRAINT [CN__TICKC_CPK_CPK_TICKC] PRIMARY KEY CLUSTERED 
(
	[CPK_TICKC] ASC
)
)
GO
ALTER TABLE [stage].[CPR_TICKC]
ADD CONSTRAINT [stage.CPR_TICKCInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]
