  CREATE TABLE [stage].[CPR_TICKCI](
	[TICKNO] [int] NOT NULL,
	[MRN] [varchar](6) NULL,
	[CONFIRMED] [varchar](1) NULL,
	[ASSIGNED] [varchar](3) NULL,
	[BILLNO] [int] NULL,
	[START] [datetime] NULL,
	[STOP] [datetime] NULL,
	[DELIVDATE] [datetime] NULL,
	[CONFDATE] [datetime] NULL,
	[RXCODE] [varchar](250) NULL,
	[RXMSG] [varchar](40) NULL,
	[RXNUM] [varchar](6) NULL,
	[KITNAME] [varchar](30) NULL,
	[SH_NAME] [varchar](100) NULL,
	[SH_ATTN] [varchar](60) NULL,
	[SH_ADDR] [varchar](40) NULL,
	[SH_CITY] [varchar](20) NULL,
	[SH_STATE] [varchar](2) NULL,
	[SH_ZIP] [varchar](10) NULL,
	[SH_PHONE] [varchar](12) NULL,
	[BI_NAME] [varchar](25) NULL,
	[BI_ATTN] [varchar](25) NULL,
	[BI_ADDR] [varchar](40) NULL,
	[BI_CITY] [varchar](20) NULL,
	[BI_STATE] [varchar](2) NULL,
	[BI_ZIP] [varchar](10) NULL,
	[BI_PHONE] [varchar](12) NULL,
	[LAST_NAME] [varchar](25) NULL,
	[FIRST_NAME] [varchar](25) NULL,
	[PAYOR] [varchar](22) NULL,
	[PICKUP] [int] NULL,
	[TOTCOST] [numeric](15, 4) NULL,
	[TOTPRICE] [numeric](15, 4) NULL,
	[TOTBPRICE] [numeric](15, 4) NULL,
	[CHOLDERNM] [varchar](32) NULL,
	[CHOLDERADR] [varchar](50) NULL,
	[CHOLDERTYP] [varchar](10) NULL,
	[CBILLTYPE] [varchar](6) NULL,
	[RPTMSG] [varchar](max) NULL,
	[STATUSPTR] [int] NULL,
	[DELIVINS] [varchar](max) NULL,
	[ENCOUNTER] [varchar](11) NULL,
	[ENT_BY] [varchar](40) NULL,
	[SH_TYPE] [varchar](40) NULL,
	[SH_METHOD] [varchar](40) NULL,
	[COPAY] [numeric](15, 4) NULL,
	[SH_SVCTYPE] [varchar](50) NULL,
	[SH_PACKAGE] [varchar](15) NULL,
	[INSNO] [int] NULL,
	[SITENO] [int] NULL,
	[DEFCOLLECT] [int] NULL,
	[ENC_HOSP] [varchar](1) NULL,
	[PI_NO] [int] NULL,
	[COMPCODE] [varchar](15) NULL,
	[DRIVER_NO] [int] NULL,
	[DEPARTDATE] [datetime] NULL,
	[SEL] [varchar](1) NULL,
	[DELFLAG] [int] NOT NULL,
	[TOUCHDATE] [datetime] NULL,
	[CHGBYHOST] [varchar](100) NULL,
	[CREATEDON] [datetime] NULL,
	[CREATEDBY] [varchar](100) NULL,
	[DTREASON] [varchar](100) NULL,
	[NOOVERRIDE] [int] NULL,
	[BATCH] [varchar](1) NULL,
	[DTCREATEDBY] [int] NULL,
	[DTCONFIRMEDBY] [int] NULL,
	[DTBILLEDBY] [int] NULL,
	[DTCREATEDDATE] [datetime] NULL,
	[DTCONFIRMEDDATE] [datetime] NULL,
	[DTBILLEDDATE] [datetime] NULL,
	[FIELDCHANGES] [int] NULL,
	[SIGNATURE] [varchar](max) NULL,
	[PALMUSER] [varchar](35) NULL,
	[RECEIVEDDATE] [datetime] NULL,
	[NUMPACKAGES] [int] NULL,
	[SELECTSN] [int] NULL,
	[ORIGINALTICKNO] [int] NULL,
	[CFK_BATCHBILLCLAIMS] [int] NULL,
	[CFK_REFSOURC] [int] NULL,
	[TIMEIN] [datetime] NULL,
	[TIMEOUT] [datetime] NULL,
	[MILEAGE] [int] NULL,
	[DELIVERED] [bit] NULL,
	[POS] [bit] NULL,
	[CFK_LOCATIONS_DEFAULT] [int] NULL,
	[PROMDATE] [datetime] NULL,
	[VERIFY] [bit] NULL,
	[ORIGINALPDF] [varchar](max) NULL,
	[STAT] [bit] NULL,
	[DP_PROMDATE] [datetime] NULL,
	[DP_DELIVEREDTIME] [datetime] NULL,
	[SIGNFORPATIENT_NAME] [varchar](100) NULL,
	[SIGNFORPATIENT_RELAT] [int] NULL,
	[DIRECTSHIP_REF] [varchar](50) NULL,
	[CFK_SUPPLIER] [int] NULL,
	[CFK_SVCTYPE] [int] NULL,
	[DIRECTSHIP_MSD] [bit] NULL,
	[DP_PROMDATE_START] [datetime] NULL,
	[CFK_TICKCI_ORIG] [int] NULL,
	[signforpatient_reas] [varchar](200) NULL,
	[onetimeinstruction] [varchar](max) NULL,
	[attempteddel] [int] NULL,
	[onetimeinstrucflag] [bit] NULL,
	[sh_latitude] [float] NULL,
	[sh_longitude] [float] NULL,
	[attemptedstatus] [bit] NULL,
	[cfk_billingreviewstat] [int] NULL,
	[billingreviewlist] [bit] NULL,
	[billingreviewcomplete] [bit] NULL,
	[cfk_pnnames_completedbillingreview] [int] NULL,
	[deliverymanagerstatus] [varchar](40) NULL,
	[deliverymanagerservicelevel] [varchar](40) NULL,
	[manuallysplit] [bit] NULL,
	[InsertDate] DATETIME,
 CONSTRAINT [CN__TICKCI_TICKNO] PRIMARY KEY CLUSTERED 
(
	[TICKNO] ASC
)
)
GO
ALTER TABLE [stage].[CPR_TICKCI]
ADD CONSTRAINT [stage.CPR_TICKCIInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]