CREATE TABLE [stage].[NG_location_mstr]
(
	[location_id] [uniqueidentifier] NOT NULL,
	[location_type] [varchar](2) NULL,
	[location_name] [varchar](40) NULL,
	[address_line_1] [varchar](55) NULL,
	[address_line_2] [varchar](55) NULL,
	[city] [varchar](35) NULL,
	[state] [varchar](3) NULL,
	[zip] [varchar](9) NULL,
	[county_id] [uniqueidentifier] NULL,
	[country_id] [uniqueidentifier] NULL,
	[phone] [varchar](10) NULL,
	[contact_last_name] [varchar](18) NULL,
	[contact_first_name] [varchar](13) NULL,
	[contact_initial] [char](1) NULL,
	[extension] [varchar](5) NULL,
	[alternate_phone] [varchar](10) NULL,
	[mammo_cert_nbr] [varchar](15) NULL,
	[site_id] [varchar](4) NULL,
	[color_code] [int] NULL,
	[clia_id] [varchar](15) NULL,
	[external_id] [varchar](20) NULL,
	[service_item_lib_id] [uniqueidentifier] NULL,
	[sim_exception_id] [uniqueidentifier] NULL,
	[ub92_bill_ind] [char](1) NOT NULL,
	[ub92_grace_period] [int] NULL,
	[location_subgrouping1_id] [uniqueidentifier] NULL,
	[location_subgrouping2_id] [uniqueidentifier] NULL,
	[dme_provider_nbr] [varchar](15) NULL,
	[alt_phone_ext] [varchar](5) NULL,
	[alt_phone_desc] [varchar](25) NULL,
	[fax] [varchar](10) NULL,
	[internal_location_ind] [char](1) NOT NULL,
	[dial_area_code] [char](1) NOT NULL,
	[fax_extras] [varchar](10) NULL,
	[bc_bs_fac_id_nbr] [char](15) NULL,
	[hcfa_box32_ind] [char](1) NOT NULL,
	[caid_fac_id_nbr] [char](15) NULL,
	[fac_entity_id] [char](2) NULL,
	[care_fac_id_nbr] [char](15) NULL,
	[location_schedulable_ind] [char](1) NOT NULL,
	[facility_location_ind] [char](1) NOT NULL,
	[note] [varchar](255) NULL,
	[delete_ind] [char](1) NOT NULL,
	[create_timestamp] [datetime] NOT NULL,
	[created_by] [int] NOT NULL,
	[modify_timestamp] [datetime] NOT NULL,
	[modified_by] [int] NOT NULL,
	[row_timestamp] [varchar](50) NOT NULL,
	[search_ahead_ind] [char](1) NOT NULL,
	[ud_directions] [varchar](1000) NULL,
	[optical_location_ind] [char](1) NOT NULL,
	[national_provider_id] [varchar](10) NULL,
	[visionweb_username] [varchar](100) NULL,
	[visionweb_password] [varchar](100) NULL,
	[image_id] [uniqueidentifier] NULL,
	[dme_national_provider_id] [varchar](10) NULL,
	[taxonomy_id] [uniqueidentifier] NULL,
	[place_of_service] [char](2) NULL,
	[loc_tax_id] [varchar](15) NULL,
	[suppress_rendering_code] [char](1) NULL,
	[tax_rate_library_id] [varchar](36) NULL,
	[et_swipe_mid] [varchar](50) NULL,
	[et_non_swipe_mid] [varchar](50) NULL,
	[et_terminal_id] [varchar](50) NULL,
	[et_store_id] [varchar](50) NULL,
	[et_merchant_id] [varchar](20) NULL,
	[et_regkey_id] [varchar](20) NULL,
	[facility_visit_type] [varchar](36) NULL,
	[healthcare_svc_location_code] [varchar](6) NULL,
	[crosswalk_charge_entry_ind] [char](1) NOT NULL,
	[crosswalk_order] [int] NULL,
	[require_surg_proc_cd_ind] [char](1) NOT NULL,
	[hos_billing_ind] [char](1) NOT NULL,
	[hos_location_ind] [char](1) NOT NULL,
	[et_txp_merchant_id] [varchar](50) NULL,
	[et_txp_regkey_id] [varchar](50) NULL,
	[et_txp_hosted_key] [varchar](50) NULL,
	[vsp_vendor_id] [varchar](100) NULL,
	[vsp_vendor_password] [varchar](100) NULL,
	[vsp_username] [varchar](100) NULL,
	[vsp_password] [varchar](100) NULL,
	[vsp_office_id] [varchar](100) NULL,
	[med_dev_tax_ind] [char](1) NOT NULL,
	[tax_gross_amount_ind] [char](1) NOT NULL,
	[opk_provider_type] [varchar](40) NULL,
	[ccbhc_location_ind] [char](1) NOT NULL,
	[address_valid_ind] [char](1) NULL,
    [InsertDate]                   DATETIME,
    CONSTRAINT [pk_location_mstr]
        PRIMARY KEY NONCLUSTERED ([location_id] ASC)
);
GO
ALTER TABLE [stage].[NG_location_mstr]
ADD CONSTRAINT [stage.NG_location_mstrInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]