CREATE TABLE [stage].[NG_patient_encounter]
(
 	[enterprise_id] [char](5) NOT NULL,
	[practice_id] [char](4) NOT NULL,
	[site_id] [char](3) NOT NULL,
	[person_id] [uniqueidentifier] NOT NULL,
	[enc_id] [uniqueidentifier] NOT NULL,
	[enc_timestamp] [datetime] NOT NULL,
	[enc_nbr] [numeric](12, 0) NOT NULL,
	[parent_enc_id] [uniqueidentifier] NULL,
	[case_id] [uniqueidentifier] NOT NULL,
	[billable_ind] [char](1) NOT NULL,
	[clinical_ind] [char](1) NOT NULL,
	[optical_ind] [char](1) NOT NULL,
	[location_id] [uniqueidentifier] NULL,
	[locked_by] [int] NULL,
	[lock_ind] [char](1) NOT NULL,
	[billable_timestamp] [datetime] NULL,
	[enc_status] [char](1) NULL,
	[complaint] [varchar](40) NULL,
	[remarks] [varchar](80) NULL,
	[user_defined1] [varchar](40) NULL,
	[user_defined2] [varchar](40) NULL,
	[user_defined3] [varchar](40) NULL,
	[user_defined4] [varchar](40) NULL,
	[guar_id] [uniqueidentifier] NULL,
	[guar_type] [char](1) NULL,
	[cob1_insured_person_id] [uniqueidentifier] NULL,
	[cob1_payer_id] [uniqueidentifier] NULL,
	[auto_accd_loc] [char](2) NULL,
	[cond_rel_emp_ind] [char](1) NOT NULL,
	[rendering_provider_id] [uniqueidentifier] NULL,
	[admit_provider_id] [uniqueidentifier] NULL,
	[admit_provider_name] [varchar](75) NULL,
	[consult1_provider_id] [uniqueidentifier] NULL,
	[consult1_provider_name] [varchar](75) NULL,
	[consult2_provider_id] [uniqueidentifier] NULL,
	[consult2_provider_name] [varchar](75) NULL,
	[refer_provider_id] [uniqueidentifier] NULL,
	[refer_provider_name] [varchar](75) NULL,
	[refer_location_id] [uniqueidentifier] NULL,
	[patient_type_id] [uniqueidentifier] NULL,
	[onset_date] [varchar](8) NULL,
	[onset_time] [varchar](4) NULL,
	[admit_date] [varchar](8) NULL,
	[discharge_date] [varchar](8) NULL,
	[accident_code] [char](1) NULL,
	[final_bill_date] [varchar](8) NULL,
	[last_bill_date] [varchar](8) NULL,
	[pat_resp_date] [varchar](8) NULL,
	[budget_ind] [char](1) NOT NULL,
	[bad_debt_prelist_date] [varchar](8) NULL,
	[print_stmt_ind] [char](1) NOT NULL,
	[last_statement_date] [varchar](8) NULL,
	[pre_list_ind] [char](1) NOT NULL,
	[pre_list_eff_date] [varchar](8) NULL,
	[agency_id] [uniqueidentifier] NULL,
	[send_coll_letter_ind] [char](1) NOT NULL,
	[collection_letter_id] [uniqueidentifier] NULL,
	[sim_prompt_ind] [char](1) NOT NULL,
	[followup_date] [varchar](8) NULL,
	[followup_ind] [char](1) NOT NULL,
	[homebound_ind] [char](1) NOT NULL,
	[reinstate_date] [varchar](8) NULL,
	[bill_hold_date] [varchar](8) NULL,
	[type_of_bill] [varchar](3) NULL,
	[supervisor_provider_id] [uniqueidentifier] NULL,
	[checkin_datetime] [datetime] NULL,
	[checkout_datetime] [datetime] NULL,
	[ub92_enc_ind] [char](1) NOT NULL,
	[ub92_linked_enc_id] [uniqueidentifier] NULL,
	[ud_billing_collections1] [varchar](40) NULL,
	[ud_billing_collections2] [varchar](40) NULL,
	[ud_billing_collections3] [varchar](40) NULL,
	[ud_billing_collections4] [varchar](40) NULL,
	[sim_emr_prompt_ind] [char](1) NOT NULL,
	[service_auth_excep_cd] [char](1) NULL,
	[same_similar_symp_date] [varchar](8) NULL,
	[last_print_statement_date] [varchar](8) NULL,
	[special_program_code] [char](2) NULL,
	[bad_debt_status_id] [uniqueidentifier] NULL,
	[cob1_person_payer_id] [uniqueidentifier] NULL,
	[lock_timestamp] [datetime] NOT NULL,
	[sliding_fee_action_ind] [char](1) NOT NULL,
	[last_seen_date] [varchar](8) NULL,
	[delay_reason_cd] [varchar](2) NULL,
	[epsdt_ref_cond_code] [varchar](20) NULL,
	[sim_ext_prompt_ind] [char](1) NOT NULL,
	[old_enc_id] [varchar](36) NULL,
	[height] [numeric](4, 1) NULL,
	[weight] [numeric](5, 1) NULL,
	[bp_systolic] [int] NULL,
	[bp_diastolic] [int] NULL,
	[pulse] [int] NULL,
	[temperature] [numeric](4, 1) NULL,
	[ud_clinical1] [varchar](40) NULL,
	[ud_clinical2] [varchar](40) NULL,
	[ud_clinical3] [varchar](40) NULL,
	[ud_clinical4] [varchar](40) NULL,
	[fqhc_enc_ind] [char](1) NOT NULL,
	[facility_location_id] [uniqueidentifier] NULL,
	[created_by] [int] NOT NULL,
	[create_timestamp] [datetime] NOT NULL,
	[modified_by] [int] NOT NULL,
	[modify_timestamp] [datetime] NOT NULL,
	[row_timestamp] [varchar](50) NOT NULL,
	[outsource_exempt_ind] [char](1) NOT NULL,
	[epsdt_ref_code] [varchar](20) NULL,
	[prim_er_billing_status] [char](1) NULL,
	[sec_er_billing_status] [char](1) NULL,
	[group_id] [uniqueidentifier] NULL,
	[group_enc_id] [uniqueidentifier] NULL,
	[incident_to_enc_ind] [char](1) NOT NULL,
	[source_product_id] [varchar](10) NULL,
	[family_planning_ind] [char](1) NOT NULL,
	[elig_data_check_ind] [char](1) NOT NULL,
	[eligibility_id] [uniqueidentifier] NULL,
	[pwk_report_type_cd] [char](2) NULL,
	[pwk_report_trans_cd] [char](2) NULL,
	[pwk_attach_ctrl_nbr] [varchar](50) NULL,
	[epsdt_enc_code] [char](2) NULL,
	[epsdt_enc_code_other] [char](2) NULL,
	[fqhc_dirty_ind] [char](1) NOT NULL,
	[fqhc_update_date] [varchar](8) NULL,
	[init_treatment_date] [varchar](8) NULL,
	[mrkt_plan_id] [uniqueidentifier] NULL,
	[mrkt_source_id] [uniqueidentifier] NULL,
	[mrkt_comments] [varchar](255) NULL,
	[mrkt_details] [varchar](255) NULL,
	[mrkt_source_type] [int] NULL,
	[casemgt_case_id] [uniqueidentifier] NULL,
	[ter_er_billing_status] [char](1) NULL,
	[ub92_initial_enc_id] [uniqueidentifier] NULL,
	[tax_rate_ind] [char](1) NOT NULL,
	[enc_timestamp_tz] [smallint] NULL,
	[billable_timestamp_tz] [smallint] NULL,
	[checkin_datetime_tz] [smallint] NULL,
	[checkout_datetime_tz] [smallint] NULL,
	[lock_timestamp_tz] [smallint] NULL,
	[create_timestamp_tz] [smallint] NULL,
	[modify_timestamp_tz] [smallint] NULL,
	[enc_tax_rate_ind] [char](1) NOT NULL,
	[uds_homeless_status_id] [uniqueidentifier] NULL,
	[pwk_report_type_cd_2] [char](2) NULL,
	[pwk_report_trans_cd_2] [char](2) NULL,
	[pwk_attach_ctrl_nbr_2] [varchar](50) NULL,
	[pwk_report_type_cd_3] [char](2) NULL,
	[pwk_report_trans_cd_3] [char](2) NULL,
	[pwk_attach_ctrl_nbr_3] [varchar](50) NULL,
	[pwk_report_type_cd_4] [char](2) NULL,
	[pwk_report_trans_cd_4] [char](2) NULL,
	[pwk_attach_ctrl_nbr_4] [varchar](50) NULL,
	[pwk_report_type_cd_5] [char](2) NULL,
	[pwk_report_trans_cd_5] [char](2) NULL,
	[pwk_attach_ctrl_nbr_5] [varchar](50) NULL,
	[pwk_report_type_cd_6] [char](2) NULL,
	[pwk_report_trans_cd_6] [char](2) NULL,
	[pwk_attach_ctrl_nbr_6] [varchar](50) NULL,
	[pwk_report_type_cd_7] [char](2) NULL,
	[pwk_report_trans_cd_7] [char](2) NULL,
	[pwk_attach_ctrl_nbr_7] [varchar](50) NULL,
	[pwk_report_type_cd_8] [char](2) NULL,
	[pwk_report_trans_cd_8] [char](2) NULL,
	[pwk_attach_ctrl_nbr_8] [varchar](50) NULL,
	[pwk_report_type_cd_9] [char](2) NULL,
	[pwk_report_trans_cd_9] [char](2) NULL,
	[pwk_attach_ctrl_nbr_9] [varchar](50) NULL,
	[pwk_report_type_cd_10] [char](2) NULL,
	[pwk_report_trans_cd_10] [char](2) NULL,
	[pwk_attach_ctrl_nbr_10] [varchar](50) NULL,
	[vision_code_category] [char](2) NULL,
	[vision_condition_ind_cd] [char](14) NULL,
	[vision_code_category_2] [char](2) NULL,
	[vision_condition_ind_cd_2] [char](14) NULL,
	[vision_code_category_3] [char](2) NULL,
	[vision_condition_ind_cd_3] [char](14) NULL,
	[not_assigned_prov_elec_ind] [char](1) NOT NULL,
	[hearing_vision_rx_date] [char](8) NULL,
	[statement_counter] [int] NOT NULL,
	[prim_enc_rate_sim] [varchar](13) NULL,
	[sec_enc_rate_sim] [varchar](13) NULL,
	[ter_enc_rate_sim] [varchar](13) NULL,
	[prim_enc_rate_amt] [numeric](19, 2) NOT NULL,
	[sec_enc_rate_amt] [numeric](19, 2) NOT NULL,
	[ter_enc_rate_amt] [numeric](19, 2) NOT NULL,
	[pm_ind] [char](1) NOT NULL,
	[convert_in_progress_ind] [char](1) NOT NULL,
	[rental_ind] [char](1) NOT NULL,
	[rental_id] [uniqueidentifier] NULL,
	[enc_changes_service_date] [char](8) NULL,
	[enc_changes_location_id] [uniqueidentifier] NULL,
	[enc_changes_payer_id] [uniqueidentifier] NULL,
	[enc_changes_person_payer_id] [uniqueidentifier] NULL,
	[enc_changes_payer_2_id] [uniqueidentifier] NULL,
	[enc_changes_person_payer_2_id] [uniqueidentifier] NULL,
	[enc_changes_payer_3_id] [uniqueidentifier] NULL,
	[enc_changes_person_payer_3_id] [uniqueidentifier] NULL,
	[enc_changes_appr_enc_id] [uniqueidentifier] NULL,
	[recalc_fail_ind] [char](1) NOT NULL,
	[claim_codes] [varchar](20) NULL,
	[wc_cond_codes] [varchar](20) NULL,
	[wc_cond_codes_other] [varchar](20) NULL,
	[medical_director_id] [uniqueidentifier] NULL,
	[anes_types_cd] [char](2) NULL,
	[anes_phys_status_cd] [char](2) NULL,
	[anes_med_dir_cd] [char](2) NULL,
	[exempt_enc_concur_ind] [char](1) NOT NULL,
	[present_induction_ind] [char](1) NOT NULL,
	[zero_bal_ind] [char](1) NOT NULL,
	[demonstration_project_id] [varchar](50) NULL,
	[csc_pri_resp_attending] [char](1) NULL,
	[csc_sec_resp_attending] [char](1) NULL,
	[csc_ter_resp_attending] [char](1) NULL,
	[csc_pri_exempt_ind] [char](1) NULL,
	[csc_sec_exempt_ind] [char](1) NULL,
	[csc_ter_exempt_ind] [char](1) NULL,
	[admit_time] [varchar](4) NULL,
	[discharge_time] [varchar](4) NULL,
	[prim_er_narrative] [varchar](255) NULL,
	[sec_er_narrative] [varchar](255) NULL,
	[ter_er_narrative] [varchar](255) NULL,
	[ordering_provider_id] [uniqueidentifier] NULL,
	[ordering_provider_name] [varchar](75) NULL,
	[csc_pri_elig_from_date] [datetime] NULL,
	[csc_pri_elig_to_date] [datetime] NULL,
	[csc_sec_elig_from_date] [datetime] NULL,
	[csc_sec_elig_to_date] [datetime] NULL,
	[csc_ter_elig_from_date] [datetime] NULL,
	[csc_ter_elig_to_date] [datetime] NULL,
	[csc_lib_timespan_id_pri] [uniqueidentifier] NULL,
	[csc_lib_timespan_id_sec] [uniqueidentifier] NULL,
	[csc_lib_timespan_id_ter] [uniqueidentifier] NULL,
	[discharge_status_cd] [char](2) NULL,
	[medications_reconciled] [char](1) NULL,
	[ccbhc_enc_ind] [char](1) NOT NULL,
	[sens_encounter_ind] [char](1) NOT NULL,
	[sens_suppress_portal_ind] [char](1) NOT NULL,
	[sens_suppress_outreach_ind] [char](1) NOT NULL,
	[program_id] [uniqueidentifier] NULL,
    [InsertDate]                   DATETIME,
    CONSTRAINT [pk_patient_encounter]
        PRIMARY KEY NONCLUSTERED ([enc_id] ASC)
);
GO
ALTER TABLE [stage].[NG_patient_encounter]
ADD CONSTRAINT [stage.NG_patient_encounterInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]