CREATE TABLE [stage].[NG_payer_mstr]
(
	[payer_id] [uniqueidentifier] NOT NULL,
	[payer_name] [varchar](40) NOT NULL,
	[plan_name] [varchar](40) NULL,
	[address_line_1] [varchar](55) NULL,
	[address_line_2] [varchar](55) NULL,
	[city] [varchar](35) NULL,
	[state] [varchar](3) NULL,
	[zip] [varchar](9) NULL,
	[country_id] [uniqueidentifier] NULL,
	[county_id] [uniqueidentifier] NULL,
	[claim_type] [char](2) NULL,
	[group_nbr] [varchar](50) NULL,
	[group_name] [varchar](33) NULL,
	[payer_nbr] [varchar](20) NULL,
	[notify_ind] [char](1) NOT NULL,
	[precert_ind] [char](1) NOT NULL,
	[verify_ind] [char](1) NOT NULL,
	[contact_last_name] [varchar](25) NULL,
	[contact_first_name] [varchar](25) NULL,
	[contact_middle_name] [varchar](25) NULL,
	[contact_phone] [varchar](10) NULL,
	[contact_ext] [char](5) NULL,
	[contact_fax] [varchar](10) NULL,
	[financial_class] [uniqueidentifier] NULL,
	[ins_type] [char](2) NULL,
	[plan_nbr] [varchar](20) NULL,
	[sig_source] [char](1) NULL,
	[medigap_id_nbr] [char](9) NULL,
	[bc_plan_code] [varchar](30) NULL,
	[copay_ind] [char](1) NOT NULL,
	[crossover_ind] [char](1) NOT NULL,
	[ins_location] [char](7) NULL,
	[medipass_ind] [char](1) NOT NULL,
	[kenpak_ind] [char](1) NOT NULL,
	[payer_id_nbr] [varchar](max) NULL,
	[kenpak_maid] [varchar](10) NULL,
	[refer_auth_req] [char](1) NULL,
	[refer_form_format] [char](7) NULL,
	[lab_fac_used] [char](6) NULL,
	[rad_fac_used] [char](6) NULL,
	[diag_code_used] [char](1) NULL,
	[dflt_accept_assgn] [char](1) NULL,
	[default_deductible] [numeric](9, 2) NULL,
	[plan_type] [varchar](4) NULL,
	[no_edit_ind] [char](1) NOT NULL,
	[external_id] [varchar](20) NULL,
	[email_address] [varchar](80) NULL,
	[disp_override_pol_nbr_ind] [char](1) NOT NULL,
	[copay_percent_ind] [char](1) NOT NULL,
	[claim_sub_type] [varchar](10) NULL,
	[activate_tos_edit_ind] [char](1) NOT NULL,
	[max_claim_charges] [int] NULL,
	[gabetterhealth_ind] [char](1) NOT NULL,
	[require_policy_nbr_ind] [char](1) NOT NULL,
	[policy_nbr_format_id] [uniqueidentifier] NULL,
	[require_group_nbr_ind] [char](1) NOT NULL,
	[group_nbr_format_id] [uniqueidentifier] NULL,
	[policy_nbr_edit_off_ind] [char](1) NOT NULL,
	[grp_nbr_edit_off_ind] [char](1) NOT NULL,
	[patientfirst_claim_type_ind] [char](1) NOT NULL,
	[nyhcra_exempt_ind] [char](1) NOT NULL,
	[nonoverride_payer_name_ind] [char](1) NOT NULL,
	[health_partners_ind] [char](1) NOT NULL,
	[bluechoiceoption_ind] [char](1) NOT NULL,
	[disable_super_bill_ind] [char](1) NOT NULL,
	[medica_ind] [char](1) NOT NULL,
	[provider_sec_ref_qual] [char](2) NULL,
	[dental_ind] [char](1) NOT NULL,
	[national_plan_id] [varchar](80) NULL,
	[alt_payer_name] [varchar](50) NULL,
	[alt_address_line_1] [varchar](55) NULL,
	[alt_address_line_2] [varchar](55) NULL,
	[alt_city] [varchar](35) NULL,
	[alt_state] [varchar](3) NULL,
	[alt_zip] [char](9) NULL,
	[alt_country_id] [uniqueidentifier] NULL,
	[alt_county_id] [uniqueidentifier] NULL,
	[alt_payer_nbr] [varchar](20) NULL,
	[alt_req_both_payments_ind] [char](1) NOT NULL,
	[alt_payer_ind] [char](1) NOT NULL,
	[alt_payer_id_nbr] [varchar](max) NULL,
	[payer_subgrouping1_id] [uniqueidentifier] NULL,
	[payer_subgrouping2_id] [uniqueidentifier] NULL,
	[payer_web_site] [varchar](120) NULL,
	[payer_alias_name] [varchar](60) NULL,
	[display_ppp_loc_cd_ind] [char](1) NOT NULL,
	[pat_ctrl_nbr_digits] [int] NULL,
	[medicare_a_ind] [char](1) NOT NULL,
	[messa_option_ind] [char](1) NOT NULL,
	[formulary_provider] [varchar](15) NULL,
	[legacy_copay_tos_1] [varchar](3) NULL,
	[legacy_copay_1] [varchar](8) NULL,
	[legacy_copay_tos_2] [varchar](3) NULL,
	[legacy_copay_2] [varchar](8) NULL,
	[med_payer_group_id] [uniqueidentifier] NULL,
	[alert_msg] [varchar](255) NULL,
	[delete_ind] [char](1) NOT NULL,
	[note] [varchar](255) NULL,
	[created_by] [int] NOT NULL,
	[modified_by] [int] NOT NULL,
	[create_timestamp] [datetime] NOT NULL,
	[modify_timestamp] [datetime] NOT NULL,
	[row_timestamp] [varchar](50) NOT NULL,
	[anes_round_cd] [char](1) NOT NULL,
	[supp_zero_claims_ind] [char](1) NOT NULL,
	[claims_never_bundle_ind] [char](1) NOT NULL,
	[disable_diag_break_ind] [char](1) NOT NULL,
	[default_resub_code] [char](1) NOT NULL,
	[anes_minutes_per_unit] [char](2) NOT NULL,
	[ndc_coding_elec_ind] [char](1) NOT NULL,
	[pur_svc_elec_ind] [char](1) NOT NULL,
	[enable_npi_code] [char](1) NULL,
	[group_taxonomy_ind] [char](1) NOT NULL,
	[require_case_mgmt_ind] [char](1) NOT NULL,
	[pat_pol_nbr_req_ind] [char](1) NOT NULL,
	[pcp_2310a_elec_ind] [char](1) NOT NULL,
	[tpl_code] [varchar](15) NULL,
	[country_code_ind] [char](1) NOT NULL,
	[ext_edit_payer_id_nbr] [varchar](20) NULL,
	[kidmed_ind] [char](1) NOT NULL,
	[amt_2300_code] [char](1) NULL,
	[cas_2300_code] [char](1) NULL,
	[cn1_2300_ind] [char](1) NOT NULL,
	[cob_popup_ind] [char](1) NOT NULL,
	[pat_resp_amt_ind] [char](1) NOT NULL,
	[alt_edit_payer_id_nbr] [varchar](20) NULL,
	[suppress_rendering_code] [char](1) NULL,
	[populate_2410CTP_ind] [char](1) NOT NULL,
	[cpt_on_revcode_rollup_ind] [char](1) NOT NULL,
	[enable_clia_elec_ind] [char](1) NOT NULL,
	[def_release_of_info] [char](2) NULL,
	[tax_rate_line_item_ind] [char](1) NOT NULL,
	[enable_ndc_elec_ind] [char](1) NOT NULL,
	[sliding_fee_ins_ind] [char](1) NOT NULL,
	[payer_rta_id_nbr] [varchar](20) NULL,
	[suppress_serv_fac_code] [char](1) NULL,
	[suppress_ref_prov_ind] [char](1) NOT NULL,
	[suppress_2320_amt_b6_ind_old] [char](1) NULL,
	[suppress_2320_amt_aae_ind_old] [char](1) NULL,
	[suppress_2430_loop_ind] [char](1) NOT NULL,
	[claim_cas_ind] [char](1) NOT NULL,
	[claim_adj_date_ind] [char](1) NOT NULL,
	[enable_2300_CN1_group_ind] [char](1) NOT NULL,
	[msp_payer_id_nbr] [varchar](60) NULL,
	[msp_payer_id_ind] [char](1) NOT NULL,
	[ndc_claim_break_ind] [char](1) NOT NULL,
	[default_rx_nbr_ind] [char](1) NOT NULL,
	[elig_ref_support_ind] [char](1) NOT NULL,
	[hsno_ind] [char](1) NOT NULL,
	[enable_2300_REF_MRN_ind] [char](1) NOT NULL,
	[diag_code_num_code] [char](1) NULL,
	[elec_sub_ssn_ind] [char](1) NOT NULL,
	[elec_pat_as_sub_ind] [char](1) NOT NULL,
	[copy_prim_resub_ind] [char](1) NOT NULL,
	[elec_dental_diags_ind] [char](1) NOT NULL,
	[elec_pur_svc_prov_ind] [char](1) NOT NULL,
	[populate_icn_nbr_ind] [char](1) NOT NULL,
	[pricing_region_lib_id] [uniqueidentifier] NULL,
	[pop2330_pri_tpl_ind] [char](1) NOT NULL,
	[pop2430_pri_tpl_ind] [char](1) NOT NULL,
	[elec_default_admit_date_ind] [char](1) NOT NULL,
	[elec_rsn_for_visit_ind] [char](1) NOT NULL,
	[elec_inst_claim_diags_ind] [char](1) NOT NULL,
	[elec_inst_claim_diags_count] [int] NOT NULL,
	[contracted_payer_ind] [char](1) NOT NULL,
	[refund_address_line1] [varchar](55) NULL,
	[refund_address_line2] [varchar](55) NULL,
	[refund_city] [varchar](35) NULL,
	[refund_state] [varchar](3) NULL,
	[refund_zip1] [varchar](9) NULL,
	[refund_country_id] [uniqueidentifier] NULL,
	[refund_county_id] [uniqueidentifier] NULL,
	[tax_exempt_ind] [char](1) NOT NULL,
	[include_tax_charges_claims_ind] [char](1) NOT NULL,
	[prop_Cas_Claim_ind] [char](1) NOT NULL,
	[prevent_COB_billing_ind] [char](1) NOT NULL,
	[pop2330_ref_pri_tpl_ind] [char](1) NOT NULL,
	[preg_on_837p_ind] [char](1) NOT NULL,
	[follows_medicare_rules_ind] [char](1) NOT NULL,
	[abn_report_path] [varchar](255) NULL,
	[diag_map_claim_ind] [char](1) NOT NULL,
	[claim_diag_map] [char](1) NULL,
	[alt_dx_ind] [char](1) NOT NULL,
	[populate_AMT_noncovered_ind] [char](1) NOT NULL,
	[populate_pat_liability_amt] [char](1) NULL,
	[altclmsendauthref] [char](1) NULL,
	[payer_exp_date] [varchar](8) NULL,
	[ordering_phys_ind] [char](1) NULL,
	[Opt_Mgmt_VSP_Payer_Ind] [char](1) NOT NULL,
	[enable_cms_rules] [char](1) NOT NULL,
	[apply_cms_rules] [char](1) NOT NULL,
	[payment_typology_code] [varchar](25) NULL,
	[practice_ordering_phys_ind] [char](1) NOT NULL,
	[payer_medicare_replace_ind] [char](1) NOT NULL,
	[main_addr_valid_ind] [char](1) NULL,
	[refund_addr_valid_ind] [char](1) NULL,
    InsertDate DATETIME
    CONSTRAINT [pk_payer_mstr]
    PRIMARY KEY CLUSTERED ([payer_id] ASC)
)
GO
ALTER TABLE [stage].[NG_payer_mstr]
ADD CONSTRAINT [stage.NG_payer_mstrInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]
