CREATE TABLE [ods].[NG_charges]
(
	[RecordID]	[INT] IDENTITY(1, 1) NOT NULL,
	[enterprise_id] [char](5) NOT NULL,
	[practice_id] [char](4) NOT NULL,
	[emr_uniq_id] [uniqueidentifier] NULL,
	[line_item_ctl] [varchar](20) NULL,
	[charge_id] [uniqueidentifier] NOT NULL,
	[person_id] [uniqueidentifier] NULL,
	[source_id] [uniqueidentifier] NULL,
	[source_type] [char](1) NULL,
	[location_id] [uniqueidentifier] NULL,
	[service_item_lib_id] [uniqueidentifier] NULL,
	[service_item_id] [varchar](12) NOT NULL,
	[cob1_amt] [numeric](19, 2) NULL,
	[cob2_amt] [numeric](19, 2) NULL,
	[cob3_amt] [numeric](19, 2) NULL,
	[pat_amt] [numeric](19, 2) NULL,
	[amt] [numeric](19, 2) NOT NULL,
	[quantity] [numeric](19, 2) NULL,
	[unit_price] [numeric](19, 2) NULL,
	[override_ind] [char](1) NOT NULL,
	[begin_date_of_service] [varchar](8) NULL,
	[end_date_of_service] [varchar](8) NULL,
	[modifier_1] [char](2) NULL,
	[modifier_2] [char](2) NULL,
	[modifier_3] [char](2) NULL,
	[modifier_4] [char](2) NULL,
	[status] [char](1) NULL,
	[rendering_id] [uniqueidentifier] NULL,
	[midlevel_id] [uniqueidentifier] NULL,
	[cpt4_code_id] [varchar](13) NULL,
	[place_of_service] [char](2) NULL,
	[icd9cm_code_id] [varchar](10) NULL,
	[icd9cm_code_id_2] [varchar](10) NULL,
	[icd9cm_code_id_3] [varchar](10) NULL,
	[icd9cm_code_id_4] [varchar](10) NULL,
	[icd9cm_code_desc] [varchar](255) NULL,
	[icd9cm_code_desc_2] [varchar](255) NULL,
	[icd9cm_code_desc_3] [varchar](255) NULL,
	[icd9cm_code_desc_4] [varchar](255) NULL,
	[invoice_desc_1] [varchar](120) NULL,
	[invoice_desc_2] [varchar](120) NULL,
	[zero_bal_date] [varchar](8) NULL,
	[proc_claim_cob1_ind] [char](1) NOT NULL,
	[proc_claim_cob2_ind] [char](1) NOT NULL,
	[proc_claim_cob3_ind] [char](1) NOT NULL,
	[pat_bal_increase_date] [varchar](8) NULL,
	[closing_date] [varchar](8) NULL,
	[seq_nbr] [smallint] NULL,
	[revenue_code] [char](4) NULL,
	[narrative] [varchar](255) NULL,
	[link_id] [uniqueidentifier] NULL,
	[exception_origin] [varchar](255) NULL,
	[external_id] [varchar](36) NULL,
	[batch_info] [varchar](40) NULL,
	[override_closing_date] [varchar](8) NULL,
	[revenue_description] [varchar](80) NULL,
	[value_code] [char](2) NULL,
	[occur_code] [char](2) NULL,
	[nyhcra_surcharge_action_ind] [char](1) NOT NULL,
	[sliding_fee_action_ind] [char](1) NOT NULL,
	[resubmission_reference_nbr] [varchar](50) NULL,
	[resubmission_cob] [int] NULL,
	[tooth] [varchar](12) NULL,
	[surface_description] [varchar](200) NULL,
	[surface] [varchar](12) NULL,
	[quadrant] [char](2) NULL,
	[form] [char](4) NULL,
	[start_time] [char](4) NULL,
	[stop_time] [char](4) NULL,
	[total_time] [char](4) NULL,
	[base_unit] [int] NULL,
	[alt_code] [varchar](10) NULL,
	[referring_name] [varchar](75) NULL,
	[referring_id] [uniqueidentifier] NULL,
	[transfer_nonpar_patpmt_ind] [char](1) NOT NULL,
	[transfer_nonpar_bal_ind] [char](1) NOT NULL,
	[anesthesia_billing_ind] [char](1) NOT NULL,
	[sim_dept_id] [uniqueidentifier] NULL,
	[note] [varchar](255) NULL,
	[create_timestamp] [datetime] NOT NULL,
	[created_by] [int] NOT NULL,
	[modify_timestamp] [datetime] NOT NULL,
	[modified_by] [int] NOT NULL,
	[row_timestamp] [varchar](50) NOT NULL,
	[outsource_ind] [char](1) NOT NULL,
	[outsource_agency_id] [uniqueidentifier] NULL,
	[outsource_date] [char](8) NULL,
	[enc_rate_ind] [char](1) NOT NULL,
	[custom_dunning_msg] [varchar](80) NULL,
	[statement_aging_date] [varchar](8) NOT NULL,
	[create_timestamp_tz] [smallint] NULL,
	[modify_timestamp_tz] [smallint] NULL,
	[batch_post_dunning_msg_id] [uniqueidentifier] NULL,
	[optik_order_id] [uniqueidentifier] NULL,
	[credit_date] [varchar](8) NULL,
	[anesthesia_units] [numeric](19, 2) NULL,
	[user_defined1_amt] [numeric](19, 2) NULL,
	[user_defined2_amt] [numeric](19, 2) NULL,
	[parent_tax_link_id] [uniqueidentifier] NULL,
	[rx_on_file_ind] [char](1) NOT NULL,
	[national_drug_code] [varchar](11) NULL,
	[NDCId] [varchar](11) NULL,
	[enc_changes_old_service_date] [char](8) NULL,
	[enc_changes_old_location_id] [uniqueidentifier] NULL,
	[behavioral_billing_ind] [char](1) NOT NULL,
	[user_defined1_unit_price] [numeric](19, 2) NULL,
	[user_defined2_unit_price] [numeric](19, 2) NULL,
	[user_defined1_override_ind] [char](1) NOT NULL,
	[user_defined2_override_ind] [char](1) NOT NULL,
	[snomed_concept_id] [varchar](18) NULL,
	[snomed_concept_id2] [varchar](18) NULL,
	[snomed_concept_id3] [varchar](18) NULL,
	[snomed_concept_id4] [varchar](18) NULL,
	[dental_ind] [char](1) NOT NULL,
	[supernumerary_ind] [char](1) NOT NULL,
	[surface_descriptor] [int] NULL,
	[defective_ind] [char](1) NOT NULL,
	[not_applicable_date] [datetime] NULL,
	[approval_date] [datetime] NULL,
	[asa_crosswalk_lib_id] [uniqueidentifier] NULL,
	[surgical_proc_code_id] [varchar](13) NULL,
	[surgical_proc_desc] [varchar](50) NULL,
	[parent_mda_link_id] [uniqueidentifier] NULL,
	[medical_director_id] [uniqueidentifier] NULL,
	[modifier_units] [numeric](19, 2) NULL,
	[time_based_units] [numeric](19, 2) NULL,
	[cob1_auth_code_id] [uniqueidentifier] NULL,
	[cob1_auth_code] [varchar](50) NULL,
	[cob1_ref_code_id] [uniqueidentifier] NULL,
	[cob1_ref_code] [varchar](50) NULL,
	[basis_of_measure] [varchar](2) NULL,
	[national_drug_units] [varchar](20) NULL,
	[cob2_auth_code_id] [uniqueidentifier] NULL,
	[cob2_auth_code] [varchar](50) NULL,
	[cob2_ref_code_id] [uniqueidentifier] NULL,
	[cob2_ref_code] [varchar](50) NULL,
	[cob3_auth_code_id] [uniqueidentifier] NULL,
	[cob3_auth_code] [varchar](50) NULL,
	[cob3_ref_code_id] [uniqueidentifier] NULL,
	[cob3_ref_code] [varchar](50) NULL,
	[cob1_resub_reference_nbr] [varchar](50) NULL,
	[cob2_resub_reference_nbr] [varchar](50) NULL,
	[cob3_resub_reference_nbr] [varchar](50) NULL,
	[NDC_eff_date] [varchar](8) NULL,
	[NDC_exp_date] [varchar](8) NULL,
	[NDC_description] [varchar](250) NULL,
	[NDC_drug_unit_price] [numeric](19, 2) NULL,
	[teeth] [varchar](64) NULL,
	[units_from_timespan1] [nvarchar](8) NULL,
	[units_from_timespan2] [nvarchar](8) NULL,
	[units_from_timespan3] [nvarchar](8) NULL,
	[unit_price_override] [money] NULL,
	[time_based_price_override_ind] [char](1) NULL,
	[icd9cm_code_id_5] [varchar](10) NULL,
	[icd9cm_code_id_6] [varchar](10) NULL,
	[icd9cm_code_id_7] [varchar](10) NULL,
	[icd9cm_code_id_8] [varchar](10) NULL,
	[icd9cm_code_id_9] [varchar](10) NULL,
	[icd9cm_code_id_10] [varchar](10) NULL,
	[icd9cm_code_id_11] [varchar](10) NULL,
	[icd9cm_code_id_12] [varchar](10) NULL,
	[icd9cm_code_desc_5] [varchar](255) NULL,
	[icd9cm_code_desc_6] [varchar](255) NULL,
	[icd9cm_code_desc_7] [varchar](255) NULL,
	[icd9cm_code_desc_8] [varchar](255) NULL,
	[icd9cm_code_desc_9] [varchar](255) NULL,
	[icd9cm_code_desc_10] [varchar](255) NULL,
	[icd9cm_code_desc_11] [varchar](255) NULL,
	[icd9cm_code_desc_12] [varchar](255) NULL,
	[ordering_id] [uniqueidentifier] NULL,
	[enc_rate_orig_cob] [int] NULL,
	[pos99location_id] [uniqueidentifier] NULL,
    [EffectiveDate] [DATETIME] NULL,
    [ExpirationDate] [DATETIME] NULL,    
    [CurrentRowFlag] [BIT] NOT NULL,
    [DeleteRowFlag] [BIT] NOT NULL,
    [InsertDate] [DATETIME] NULL,
    [UpdateDate] [DATETIME] NULL,
    CONSTRAINT [PKods.NG_charges.RecordID]
        PRIMARY KEY CLUSTERED ([RecordID] ASC)
) ON [PRIMARY]
GO
ALTER TABLE [ods].[NG_charges]
ADD CONSTRAINT [ods.NG_chargesEffectiveDate]
    DEFAULT (GETDATE()) FOR [EffectiveDate]
GO
ALTER TABLE [ods].[NG_charges]
ADD CONSTRAINT [ods.NG_chargesDeleteRowFlag]
    DEFAULT ((0)) FOR [DeleteRowFlag]
GO
ALTER TABLE [ods].[NG_charges]
ADD CONSTRAINT [ods.NG_chargesInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]
GO