CREATE TABLE [ods].[NG_PIVC_Infusion_]
(
	[RecordID]					[INT] IDENTITY(1, 1) NOT NULL,
 	[enterprise_id] [char](5) NOT NULL,
	[practice_id] [char](4) NOT NULL,
	[person_id] [uniqueidentifier] NOT NULL,
	[enc_id] [uniqueidentifier] NOT NULL,
	[created_by] [int] NOT NULL,
	[create_timestamp] [datetime] NOT NULL,
	[modified_by] [int] NOT NULL,
	[modify_timestamp] [datetime] NOT NULL,
	[create_timestamp_tz] [smallint] NULL,
	[modify_timestamp_tz] [smallint] NULL,
	[row_timestamp] [varchar](50) NOT NULL,
	[Diagnosis1_Code] [varchar](10) NULL,
	[Diagnosis1_Description] [varchar](255) NULL,
	[Diagnosis2_Code] [varchar](10) NULL,
	[Diagnosis2_Description] [varchar](255) NULL,
	[Diagnosis3_Code] [varchar](10) NULL,
	[Diagnosis3_Description] [varchar](255) NULL,
	[Discharge_BP] [varchar](7) NULL,
	[Discharge_HR] [varchar](3) NULL,
	[Discharge_Instn_Given] [int] NULL,
	[Discharge_Instructions] [varchar](1000) NULL,
	[Discharge_Pain] [int] NULL,
	[Discharge_RR] [varchar](3) NULL,
	[Discharge_SpO2] [varchar](7) NULL,
	[Discharge_Temp] [varchar](6) NULL,
	[Discharge_Vitals_Time] [varchar](5) NULL,
	[Final_Sign_Date] [varchar](10) NULL,
	[Final_Sign_InvBillingError] [varchar](255) NULL,
	[Final_Sign_InvBillingUpdate] [varchar](10) NULL,
	[Final_Sign_Time] [varchar](5) NULL,
	[Final_Signed_By] [varchar](75) NULL,
	[Internal_Provider_id] [varchar](36) NULL,
	[Internal_Provider_Name] [varchar](75) NULL,
	[Ivstart_Access] [varchar](25) NULL,
	[Ivstart_Central_Line] [varchar](25) NULL,
	[Ivstart_Lumen_Count] [varchar](25) NULL,
	[Ivstart_Midline_Type] [varchar](25) NULL,
	[Ivstart_OtherAccess] [varchar](25) NULL,
	[Ivstart_PICC_ArmCircum] [int] NULL,
	[Ivstart_PICC_Pulled] [int] NULL,
	[Ivstart_PICC_Type] [varchar](25) NULL,
	[Ivstart_PIV] [int] NULL,
	[Ivstart_PIV_Attempts] [int] NULL,
	[Ivstart_PIV_Location] [varchar](25) NULL,
	[Ivstart_PIV_Vein] [varchar](25) NULL,
	[Ivstart_PORT_AccessedToday] [int] NULL,
	[Ivstart_PORT_Type] [varchar](25) NULL,
	[LMP_NA] [int] NULL,
	[Location_id] [varchar](36) NULL,
	[Med_Provided] [varchar](4) NULL,
	[No_Medications] [int] NULL,
	[Order_Description] [varchar](100) NULL,
	[Order_seq_no] [varchar](36) NULL,
	[Ordering_Provider_id] [varchar](36) NULL,
	[Ordering_Provider_Name] [varchar](75) NULL,
	[Partial_Sign_Date] [varchar](10) NULL,
	[Partial_Sign_Time] [varchar](5) NULL,
	[Partial_Signed_By] [varchar](75) NULL,
	[Patient_Wt_Kg] [int] NULL,
	[Patient_Wt_lbs] [int] NULL,
	[pe_Accompanied_by] [varchar](50) NULL,
	[pe_Ambulatory] [varchar](20) NULL,
	[pe_Cardio_Comments] [varchar](max) NULL,
	[pe_Cardio_Edema] [int] NULL,
	[pe_Cardio_HRR] [int] NULL,
	[pe_Distress] [int] NULL,
	[pe_Distress_Comments] [varchar](50) NULL,
	[pe_Gastro_ABDSoft] [int] NULL,
	[pe_Gastro_BSounds] [int] NULL,
	[pe_Gastro_Comments] [varchar](max) NULL,
	[pe_Gastro_Tender] [int] NULL,
	[pe_IVSite_CleanDry] [int] NULL,
	[pe_IVSite_Comments] [varchar](max) NULL,
	[pe_IVSite_Pain] [int] NULL,
	[pe_IVSite_Redness] [int] NULL,
	[pe_IVSite_SSInfection] [int] NULL,
	[pe_Neuro_Comments] [varchar](max) NULL,
	[pe_Neuro_Normal] [int] NULL,
	[pe_Neuro_Pain] [int] NULL,
	[pe_Neuro_PERRLA] [int] NULL,
	[pe_Oriented] [int] NULL,
	[pe_Oriented_Comments] [varchar](max) NULL,
	[pe_Other_Comments] [varchar](max) NULL,
	[pe_Pulmonary_Comments] [varchar](max) NULL,
	[pe_Pulmonary_DecreasedBS] [int] NULL,
	[pe_Pulmonary_LungsClear] [int] NULL,
	[pe_Pulmonary_SOB] [int] NULL,
	[pe_Pulmonary_Wheezes] [int] NULL,
	[pe_Skin_Color] [varchar](20) NULL,
	[pe_Skin_Comments] [varchar](max) NULL,
	[pe_Skin_OralMuscosa] [varchar](20) NULL,
	[pe_Skin_Turgor] [varchar](20) NULL,
	[pe_Skin_WarmDry_Cool] [int] NULL,
	[pre_Chest_Xray] [int] NULL,
	[pre_EpiPen] [int] NULL,
	[pre_EpiPen_Expiry] [varchar](7) NULL,
	[pre_EpiPen_Guide] [int] NULL,
	[pre_HepB] [int] NULL,
	[pre_TB_Test] [int] NULL,
	[PRN_Sign_Date] [varchar](10) NULL,
	[PRN_Sign_Time] [varchar](5) NULL,
	[PRN_Signed_By] [varchar](75) NULL,
	[PRNMeds] [int] NULL,
	[Service_Location] [varchar](40) NULL,
	[Total_Infusion_Time] [varchar](5) NULL,
	[delete_ind] [varchar](1) NULL,
	[Created_By_Name] [varchar](75) NULL,
	[LMP_Notes] [varchar](150) NULL,
	[Addl_Narrative_Notes] [varchar](max) NULL,
	[Discharge_Letter_Text] [varchar](max) NULL,
	[Discharge_Letter_Action] [varchar](20) NULL,
	[Discharge_Letter_User] [varchar](75) NULL,
	[Ivstart_Injection_Site] [varchar](25) NULL,
	[Inventory_Interface] [varchar](5) NULL,
	[Ivstart_Injection_Site2] [varchar](25) NULL,
	[Ivstart_Injection_Site3] [varchar](25) NULL,
	[Premeds_Declined] [int] NULL,
	[Chair_Time] [int] NULL,
	[EffectiveDate] [DATETIME] NULL,
    [ExpirationDate] [DATETIME] NULL,    
    [CurrentRowFlag] [BIT] NOT NULL,
    [DeleteRowFlag] [BIT] NOT NULL,
    [InsertDate] [DATETIME] NULL,
    [UpdateDate] [DATETIME] NULL,
    CONSTRAINT [PKods.NG_PIVC_Infusion_.RecordID]
        PRIMARY KEY CLUSTERED ([RecordID] ASC)
) ON [PRIMARY]
GO
ALTER TABLE [ods].[NG_PIVC_Infusion_]
ADD CONSTRAINT [ods.NG_PIVC_Infusion_EffectiveDate]
    DEFAULT (GETDATE()) FOR [EffectiveDate]
GO
ALTER TABLE [ods].[NG_PIVC_Infusion_]
ADD CONSTRAINT [ods.NG_PIVC_Infusion_DeleteRowFlag]
    DEFAULT ((0)) FOR [DeleteRowFlag]
GO
ALTER TABLE [ods].[NG_PIVC_Infusion_]
ADD CONSTRAINT [ods.NG_PIVC_Infusion_InsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]
GO