CREATE TABLE [ods].[NG_person]
(
	[RecordID]					[INT] IDENTITY(1, 1) NOT NULL,
    [enterprise_id]                [CHAR](5)          NOT NULL,
    [practice_id]                  [CHAR](4)          NOT NULL,
    [person_id]                    [UNIQUEIDENTIFIER] NOT NULL,
    [site_id]                      [CHAR](3)          NOT NULL,
    [person_nbr]                   [CHAR](12)         NOT NULL,
    [other_id_number]              [VARCHAR](15)      NULL,
    [last_name]                    [VARCHAR](60)      NOT NULL,
    [first_name]                   [VARCHAR](60)      NOT NULL,
    [middle_name]                  [VARCHAR](25)      NULL,
    [suffix]                       [VARCHAR](100)     NULL,
    [prefix]                       [VARCHAR](12)      NULL,
    [degree]                       [VARCHAR](12)      NULL,
    [prior_last_name]              [VARCHAR](40)      NULL,
    [address_line_1]               [VARCHAR](55)      NULL,
    [address_line_2]               [VARCHAR](55)      NULL,
    [city]                         [VARCHAR](35)      NULL,
    [state]                        [VARCHAR](3)       NULL,
    [zip]                          [VARCHAR](9)       NULL,
    [country]                      [VARCHAR](100)     NULL,
    [county]                       [VARCHAR](100)     NULL,
    [country_id]                   [UNIQUEIDENTIFIER] NULL,
    [county_id]                    [UNIQUEIDENTIFIER] NULL,
    [home_phone]                   [VARCHAR](10)      NULL,
    [sec_address_line_1]           [VARCHAR](55)      NULL,
    [sec_address_line_2]           [VARCHAR](55)      NULL,
    [sec_city]                     [VARCHAR](35)      NULL,
    [sec_state]                    [CHAR](3)          NULL,
    [sec_zip]                      [VARCHAR](9)       NULL,
    [sec_country_id]               [UNIQUEIDENTIFIER] NULL,
    [sec_county_id]                [UNIQUEIDENTIFIER] NULL,
    [sec_country]                  [VARCHAR](100)     NULL,
    [sec_county]                   [VARCHAR](100)     NULL,
    [sec_home_phone]               [VARCHAR](10)      NULL,
    [day_phone]                    [VARCHAR](10)      NULL,
    [day_phone_ext]                [VARCHAR](10)      NULL,
    [alt_phone]                    [VARCHAR](10)      NULL,
    [alt_phone_desc]               [VARCHAR](25)      NULL,
    [alt_phone_ext]                [VARCHAR](5)       NULL,
    [date_of_birth]                [VARCHAR](8)       NULL,
    [sex]                          [CHAR](1)          NULL,
    [ssn]                          [CHAR](9)          NULL,
    [marital_status]               [CHAR](1)          NULL,
    [expired_ind]                  [CHAR](1)          NOT NULL,
    [expired_date]                 [VARCHAR](8)       NULL,
    [smoker_ind]                   [CHAR](1)          NOT NULL,
    [veteran_ind]                  [CHAR](1)          NOT NULL,
    [race_id]                      [UNIQUEIDENTIFIER] NULL,
    [language_id]                  [UNIQUEIDENTIFIER] NULL,
    [religion_id]                  [UNIQUEIDENTIFIER] NULL,
    [church_id]                    [UNIQUEIDENTIFIER] NULL,
    [race]                         [VARCHAR](100)     NULL,
    [language]                     [VARCHAR](100)     NULL,
    [religion]                     [VARCHAR](100)     NULL,
    [church]                       [VARCHAR](100)     NULL,
    [student_status]               [CHAR](1)          NULL,
    [primarycare_prov_id]          [UNIQUEIDENTIFIER] NULL,
    [primarycare_prov_name]        [VARCHAR](75)      NULL,
    [image_id]                     [UNIQUEIDENTIFIER] NULL,
    [external_id]                  [VARCHAR](20)      NULL,
    [email_address]                [VARCHAR](80)      NULL,
    [int_home_phone]               [VARCHAR](20)      NULL,
    [int_work_phone]               [VARCHAR](20)      NULL,
    [int_zip]                      [VARCHAR](12)      NULL,
    [created_by]                   [INT]              NOT NULL,
    [create_timestamp]             [DATETIME]         NOT NULL,
    [modified_by]                  [INT]              NOT NULL,
    [modify_timestamp]             [DATETIME]         NOT NULL,
    [row_timestamp]                [VARCHAR](50)        NOT NULL,
    [nickname]                     [VARCHAR](60)      NULL,
    [uds_homeless_status_id]       [UNIQUEIDENTIFIER] NULL,
    [uds_migrant_worker_status_id] [UNIQUEIDENTIFIER] NULL,
    [uds_language_barrier_id]      [UNIQUEIDENTIFIER] NULL,
    [uds_primary_med_coverage_id]  [UNIQUEIDENTIFIER] NULL,
    [note]                         [VARCHAR](255)     NULL,
    [contact_seq]                  [VARCHAR](10)      NULL,
    [home_phone_comment]           [VARCHAR](50)      NULL,
    [day_phone_comment]            [VARCHAR](50)      NULL,
    [alt_phone_comment]            [VARCHAR](50)      NULL,
    [sec_home_phone_comment]       [VARCHAR](50)      NULL,
    [email_address_comment]        [VARCHAR](50)      NULL,
    [contact_pref_id]              [UNIQUEIDENTIFIER] NULL,
    [contact_pref_desc]            [VARCHAR](50)      NULL,
    [contact_alert_ind]            [CHAR](1)          NOT NULL,
    [uds_pub_hsng_pri_care_id]     [UNIQUEIDENTIFIER] NULL,
    [uds_school_hlth_ctr_id]       [UNIQUEIDENTIFIER] NULL,
    [self_pay_ind]                 [CHAR](1)          NOT NULL,
    [uds_race_id]                  [UNIQUEIDENTIFIER] NULL,
    [uds_ethnicity_id]             [UNIQUEIDENTIFIER] NULL,
    [uds_tribal_affiliation_id]    [UNIQUEIDENTIFIER] NULL,
    [uds_blood_quantum_id]         [UNIQUEIDENTIFIER] NULL,
    [uds_veteran_status]           [CHAR](1)          NULL,
    [uds_consent_to_treat_ind]     [CHAR](1)          NOT NULL,
    [community_code_old]           [VARCHAR](200)     NULL,
    [mothers_maiden_name]          [VARCHAR](60)      NULL,
    [create_timestamp_tz]          [SMALLINT]         NULL,
    [modify_timestamp_tz]          [SMALLINT]         NULL,
    [uds_ihs_elig_status_id]       [UNIQUEIDENTIFIER] NULL,
    [uds_tribal_class_id]          [UNIQUEIDENTIFIER] NULL,
    [uds_decendancy_id]            [UNIQUEIDENTIFIER] NULL,
    [uds_consent_to_treat_date]    [CHAR](8)          NULL,
    [community_code_id]            [UNIQUEIDENTIFIER] NULL,
    [ethnicity]                    [VARCHAR](40)      NULL,
    [ethnicity_id]                 [UNIQUEIDENTIFIER] NULL,
    [primary_dental_prov_id]       [UNIQUEIDENTIFIER] NULL,
    [primary_dental_prov_name]     [VARCHAR](30)      NULL,
    [cell_phone]                   [VARCHAR](10)      NULL,
    [cell_phone_comment]           [VARCHAR](50)      NULL,
    [address_type]                 [VARCHAR](100)     NULL,
    [sec_address_type]             [VARCHAR](100)     NULL,
    [address_type_id]              [UNIQUEIDENTIFIER] NULL,
    [sec_address_type_id]          [UNIQUEIDENTIFIER] NULL,
    [soundex_last_name]            [CHAR](4)          NOT NULL,
    [soundex_first_name]           [CHAR](4)          NOT NULL,
    [prefix_id]                    [UNIQUEIDENTIFIER] NULL,
    [suffix_id]                    [UNIQUEIDENTIFIER] NULL,
    [prefix_old]                   [VARCHAR](12)      NULL,
    [suffix_old]                   [VARCHAR](12)      NULL,
    [cause_of_death_code]          [VARCHAR](10)      NULL,
    [cause_of_death]               [VARCHAR](255)     NULL,
    [birth_mothers_lname]          [VARCHAR](60)      NULL,
    [birth_mothers_fname]          [VARCHAR](60)      NULL,
    [birth_mothers_mname]          [VARCHAR](60)      NULL,
    [expired_time]                 [DATETIME]         NULL,
    [expired_time_tz]              [SMALLINT]         NULL,
    [email_ind]                    [CHAR](1)          NOT NULL,
    [phone_ind]                    [CHAR](1)          NOT NULL,
    [portal_ind]                   [CHAR](1)          NOT NULL,
    [sms_ind]                      [CHAR](1)          NOT NULL,
    [voice_ind]                    [CHAR](1)          NOT NULL,
    [optout_ind]                   [CHAR](1)          NOT NULL,
    [notific_pref_ind]             [CHAR](1)          NOT NULL,
    [person_merge_station_id]      [VARCHAR](50)      NULL,
    [person_merge_flag]            [CHAR](1)          NULL,
    [risk_level]                   [CHAR](10)         NULL,
    [exempt_frm_person_merge]      [CHAR](1)          NOT NULL,
    [image_id_4frontimage]         [UNIQUEIDENTIFIER] NULL,
    [image_id_4barcodeImage]       [UNIQUEIDENTIFIER] NULL,
    [sexual_orientation]           [CHAR](50)         NULL,
    [preferred_pronoun]            [CHAR](50)         NULL,
    [enable_home_phone_ind]        [CHAR](1)          NOT NULL,
    [enable_cell_phone_ind]        [CHAR](1)          NOT NULL,
    [enable_email_address_ind]     [CHAR](1)          NOT NULL,
    [enable_alt_phone_ind]         [CHAR](1)          NOT NULL,
    [enable_day_phone_ind]         [CHAR](1)          NOT NULL,
    [enable_sec_hm_phone_ind]      [CHAR](1)          NOT NULL,
    [enable_int_phone_ind]         [CHAR](1)          NOT NULL,
    [current_gender]               [VARCHAR](25)      NULL,
    [previous_first_name]          [VARCHAR](60)      NULL,
    [other_reason_so]              [VARCHAR](50)      NULL,
    [billing_addr_valid_ind]       [CHAR](1)          NULL,
    [secondary_addr_valid_ind]     [CHAR](1)          NULL,
    [per_corr_lang]                [VARCHAR](8)       NOT NULL,
    [contact_seq_edi]              [VARCHAR](10)      NULL,
    [EffectiveDate] [DATETIME] NULL,
    [ExpirationDate] [DATETIME] NULL,    
    [CurrentRowFlag] [BIT] NOT NULL,
    [DeleteRowFlag] [BIT] NOT NULL,
    [InsertDate] [DATETIME] NULL,
    [UpdateDate] [DATETIME] NULL,
    CONSTRAINT [PKods.NG_person.RecordID]
        PRIMARY KEY CLUSTERED ([RecordID] ASC)
) ON [PRIMARY]
GO
ALTER TABLE [ods].[NG_person]
ADD CONSTRAINT [ods.NG_personEffectiveDate]
    DEFAULT (GETDATE()) FOR [EffectiveDate]
GO
ALTER TABLE [ods].[NG_person]
ADD CONSTRAINT [ods.NG_personDeleteRowFlag]
    DEFAULT ((0)) FOR [DeleteRowFlag]
GO
ALTER TABLE [ods].[NG_person]
ADD CONSTRAINT [ods.NG_personInsertDate]
    DEFAULT (GETDATE()) FOR [InsertDate]
GO